server.port=8001
spring.application.name=auth-service

spring.profiles.active=local

app.internal.api-key=${INTERNAL_API_KEY}
app.services.notification-report.url=http://localhost:8005

# TrustedDevice Config
app.auth.trusted-device.cookie-secure=false
app.auth.trusted-device.days=7
