server.port=8001
spring.application.name=auth-service

spring.profiles.active=local

app.internal.api-key=super-secret-internal-key-for-orchestria-2026
app.services.notification-report.url=http://localhost:8005

# TrustedDevice Config
app.auth.trusted-device.cookie-secure=false
app.auth.trusted-device.days=7
