package com.pangeranvalerensco.orchestria.request_service.entity.enums;

public enum FundRequestStatus {
    DRAFT,
    SUBMITTED,
    DIVISION_APPROVED,
    PUB_APPROVED,
    PEMBINA_APPROVED,
    REVISION_REQUESTED,
    REJECTED,
    READY_FOR_DISBURSEMENT,
    DISBURSED,
    FUND_RECEIVED,
    SETTLEMENT_SUBMITTED,
    SETTLEMENT_REVISION_REQUIRED,
    SETTLEMENT_APPROVED,
    COMPLETED,
    CANCELLED
}
