--
-- PostgreSQL database dump
--

\restrict UFHA9R0QJYyhDSH4rQhcUjBivS8un1UNmI0F7Y5UD0lzoRTMgkWZjkFoJDpdBAB

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-06-22 23:50:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5188 (class 1262 OID 57459)
-- Name: orchestria_organization_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE orchestria_organization_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE orchestria_organization_db OWNER TO postgres;

\unrestrict UFHA9R0QJYyhDSH4rQhcUjBivS8un1UNmI0F7Y5UD0lzoRTMgkWZjkFoJDpdBAB
\connect orchestria_organization_db
\restrict UFHA9R0QJYyhDSH4rQhcUjBivS8un1UNmI0F7Y5UD0lzoRTMgkWZjkFoJDpdBAB

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 234 (class 1259 OID 66089)
-- Name: archive_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.archive_documents (
    id bigint NOT NULL,
    category character varying(50) NOT NULL,
    content_type character varying(200) NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by_email character varying(500),
    description text,
    lock_version bigint,
    original_file_name character varying(500) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_reference character varying(1000) NOT NULL,
    stored_file_name character varying(500) NOT NULL,
    title character varying(500) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    uploaded_by_email character varying(500) NOT NULL,
    uploaded_by_name character varying(500),
    CONSTRAINT archive_documents_category_check CHECK (((category)::text = ANY ((ARRAY['SURAT_MASUK'::character varying, 'SURAT_KELUAR'::character varying, 'PROPOSAL'::character varying, 'LAPORAN'::character varying, 'NOTULEN'::character varying, 'DOKUMENTASI'::character varying, 'LAINNYA'::character varying])::text[])))
);


ALTER TABLE public.archive_documents OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 66088)
-- Name: archive_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.archive_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.archive_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 66151)
-- Name: asset_borrowings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asset_borrowings (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    actual_return_date date,
    approved_at timestamp(6) without time zone,
    approved_by_email character varying(255),
    borrow_date date NOT NULL,
    borrower_auth_user_id bigint,
    borrower_email character varying(255) NOT NULL,
    borrower_member_id bigint NOT NULL,
    borrower_name character varying(255) NOT NULL,
    cancellation_reason character varying(255),
    condition_after character varying(255),
    condition_before character varying(255),
    created_at timestamp(6) without time zone,
    expected_return_date date NOT NULL,
    handed_over_at timestamp(6) without time zone,
    handed_over_by_email character varying(255),
    handover_proof_url character varying(255),
    note character varying(255),
    purpose character varying(1000) NOT NULL,
    rejection_reason character varying(255),
    return_proof_url character varying(255),
    return_requested_at timestamp(6) without time zone,
    return_verified_at timestamp(6) without time zone,
    return_verified_by_email character varying(255),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    asset_id character varying(255) NOT NULL,
    CONSTRAINT asset_borrowings_condition_after_check CHECK (((condition_after)::text = ANY ((ARRAY['GOOD'::character varying, 'MINOR_DAMAGE'::character varying, 'DAMAGED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT asset_borrowings_condition_before_check CHECK (((condition_before)::text = ANY ((ARRAY['GOOD'::character varying, 'MINOR_DAMAGE'::character varying, 'DAMAGED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT asset_borrowings_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'BORROWED'::character varying, 'RETURN_REQUESTED'::character varying, 'RETURN_VERIFIED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.asset_borrowings OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 66171)
-- Name: asset_condition_histories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asset_condition_histories (
    id character varying(255) NOT NULL,
    checked_at timestamp(6) without time zone NOT NULL,
    checked_by_email character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    new_condition character varying(255) NOT NULL,
    new_status character varying(255) NOT NULL,
    note character varying(255),
    old_condition character varying(255),
    old_status character varying(255),
    asset_id character varying(255) NOT NULL,
    borrowing_id character varying(255),
    CONSTRAINT asset_condition_histories_new_condition_check CHECK (((new_condition)::text = ANY ((ARRAY['GOOD'::character varying, 'MINOR_DAMAGE'::character varying, 'DAMAGED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT asset_condition_histories_new_status_check CHECK (((new_status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'RESERVED'::character varying, 'BORROWED'::character varying, 'MAINTENANCE'::character varying, 'LOST'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT asset_condition_histories_old_condition_check CHECK (((old_condition)::text = ANY ((ARRAY['GOOD'::character varying, 'MINOR_DAMAGE'::character varying, 'DAMAGED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT asset_condition_histories_old_status_check CHECK (((old_status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'RESERVED'::character varying, 'BORROWED'::character varying, 'MAINTENANCE'::character varying, 'LOST'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.asset_condition_histories OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 66188)
-- Name: assets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assets (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    asset_code character varying(50) NOT NULL,
    asset_name character varying(150) NOT NULL,
    category character varying(100) NOT NULL,
    created_at timestamp(6) without time zone,
    current_condition character varying(255) NOT NULL,
    current_status character varying(255) NOT NULL,
    description character varying(1000),
    image_url character varying(500),
    location character varying(200),
    responsible_member_id bigint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT assets_current_condition_check CHECK (((current_condition)::text = ANY ((ARRAY['GOOD'::character varying, 'MINOR_DAMAGE'::character varying, 'DAMAGED'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT assets_current_status_check CHECK (((current_status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'RESERVED'::character varying, 'BORROWED'::character varying, 'MAINTENANCE'::character varying, 'LOST'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.assets OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 66204)
-- Name: cleanliness_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cleanliness_assignments (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    attendance_note text,
    attendance_status character varying(255) NOT NULL,
    attended_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    evidence_url character varying(255),
    member_email character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    member_name character varying(255) NOT NULL,
    recorded_by_email character varying(255),
    updated_at timestamp(6) without time zone,
    schedule_id character varying(255) NOT NULL,
    CONSTRAINT cleanliness_assignments_attendance_status_check CHECK (((attendance_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PRESENT'::character varying, 'ABSENT'::character varying, 'EXCUSED'::character varying])::text[])))
);


ALTER TABLE public.cleanliness_assignments OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 66219)
-- Name: cleanliness_point_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cleanliness_point_records (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    member_id bigint NOT NULL,
    member_name character varying(255) NOT NULL,
    point_value integer NOT NULL,
    reason text NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL,
    recorded_by_email character varying(255) NOT NULL,
    schedule_id character varying(255),
    type character varying(255) NOT NULL,
    CONSTRAINT cleanliness_point_records_type_check CHECK (((type)::text = ANY ((ARRAY['REWARD'::character varying, 'VIOLATION'::character varying])::text[])))
);


ALTER TABLE public.cleanliness_point_records OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 66236)
-- Name: cleanliness_schedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cleanliness_schedules (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_email character varying(255) NOT NULL,
    description text,
    duty_date date NOT NULL,
    end_time time(0) without time zone NOT NULL,
    location character varying(255) NOT NULL,
    start_time time(0) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT cleanliness_schedules_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.cleanliness_schedules OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 57461)
-- Name: division_task_evidences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.division_task_evidences (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000),
    external_link character varying(500),
    file_url character varying(500),
    title character varying(150) NOT NULL,
    type character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    task_id bigint NOT NULL,
    submitted_by_member_id bigint,
    CONSTRAINT division_task_evidences_type_check CHECK (((type)::text = ANY ((ARRAY['PHOTO'::character varying, 'DOCUMENT'::character varying, 'LINK'::character varying, 'NOTE'::character varying])::text[])))
);


ALTER TABLE public.division_task_evidences OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 57460)
-- Name: division_task_evidences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.division_task_evidences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.division_task_evidences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 57477)
-- Name: division_tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.division_tasks (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000),
    due_date date,
    priority character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    assigned_member_id bigint,
    division_id bigint NOT NULL,
    CONSTRAINT division_tasks_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT division_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.division_tasks OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 57476)
-- Name: division_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.division_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.division_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 57495)
-- Name: divisions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.divisions (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    public_visible boolean NOT NULL
);


ALTER TABLE public.divisions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 57494)
-- Name: divisions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.divisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.divisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 66253)
-- Name: english_activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.english_activities (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    activity_date date NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_email character varying(255) NOT NULL,
    description text,
    end_time time(0) without time zone NOT NULL,
    start_time time(0) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    topic character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT english_activities_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.english_activities OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 66270)
-- Name: english_deposits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.english_deposits (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    evidence_url character varying(1000) NOT NULL,
    member_email character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    member_name character varying(255) NOT NULL,
    score numeric(5,2),
    status character varying(255) NOT NULL,
    submission_note text,
    submitted_at timestamp(6) without time zone NOT NULL,
    topic character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    verification_note text,
    verified_at timestamp(6) without time zone,
    verified_by_email character varying(255),
    activity_id character varying(255) NOT NULL,
    CONSTRAINT english_deposits_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying, 'MISSED'::character varying])::text[])))
);


ALTER TABLE public.english_deposits OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 57509)
-- Name: member_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member_assignments (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    division_id bigint NOT NULL,
    member_id bigint NOT NULL,
    period_id bigint NOT NULL,
    position_id bigint NOT NULL,
    CONSTRAINT member_assignments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.member_assignments OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 57508)
-- Name: member_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.member_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 57525)
-- Name: members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    active boolean NOT NULL,
    auth_user_id bigint,
    cohort character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(150) NOT NULL,
    phone_number character varying(30),
    status character varying(30) NOT NULL,
    student_number character varying(50),
    updated_at timestamp(6) without time zone NOT NULL,
    campus_class character varying(100),
    display_order integer NOT NULL,
    major character varying(100),
    profile_photo_url character varying(500),
    public_visible boolean NOT NULL,
    CONSTRAINT members_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ALUMNI'::character varying])::text[])))
);


ALTER TABLE public.members OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 57524)
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 57541)
-- Name: organization_periods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organization_periods (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_date date,
    active boolean CONSTRAINT organization_periods_is_active_not_null NOT NULL,
    name character varying(100) NOT NULL,
    start_date date,
    updated_at timestamp(6) without time zone NOT NULL,
    current_period boolean NOT NULL,
    public_visible boolean NOT NULL
);


ALTER TABLE public.organization_periods OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 57540)
-- Name: organization_periods_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.organization_periods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_periods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 57552)
-- Name: positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.positions (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    level_order integer NOT NULL,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    public_visible boolean NOT NULL
);


ALTER TABLE public.positions OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 57551)
-- Name: positions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 66288)
-- Name: public_content_entries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.public_content_entries (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    author_name character varying(255),
    author_role character varying(255),
    body text,
    category character varying(100),
    content_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_email character varying(100),
    display_order integer NOT NULL,
    event_date date,
    link_url character varying(2000),
    media_url character varying(2000),
    publication_status character varying(255) NOT NULL,
    published_at timestamp(6) without time zone,
    status_label character varying(100),
    subtitle character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by_email character varying(100),
    CONSTRAINT public_content_entries_content_type_check CHECK (((content_type)::text = ANY ((ARRAY['HERO'::character varying, 'ABOUT'::character varying, 'VISION'::character varying, 'MISSION'::character varying, 'PROGRAM'::character varying, 'FACILITY'::character varying, 'TESTIMONIAL'::character varying, 'ACTIVITY'::character varying, 'MEDIA'::character varying])::text[]))),
    CONSTRAINT public_content_entries_publication_status_check CHECK (((publication_status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying])::text[])))
);


ALTER TABLE public.public_content_entries OWNER TO postgres;

--
-- TOC entry 5173 (class 0 OID 66089)
-- Dependencies: 234
-- Data for Name: archive_documents; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.archive_documents VALUES (1, 'LAPORAN', 'application/pdf', false, NULL, NULL, 'ini daftar penempatan magang', 0, 'Daftar_Penempatan_Magang_PUB_20250-2026.pdf', 479584, '81937f7f-96de-4d76-a79d-8e4302c12f8d.pdf', '81937f7f-96de-4d76-a79d-8e4302c12f8d.pdf', 'Daftar Penempatan Magang', '2026-06-21 03:46:45.973912', 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', NULL);
INSERT INTO public.archive_documents VALUES (2, 'PROPOSAL', 'application/pdf', false, NULL, NULL, NULL, 0, 'PROPOSAL KEGIATAN MAKRAB HIMATIF 2026.pdf', 550805, 'be49fe19-4d76-447d-ad71-f53de32ff8de.pdf', 'be49fe19-4d76-447d-ad71-f53de32ff8de.pdf', 'Proposal Makrab', '2026-06-21 03:47:38.461835', 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', NULL);
INSERT INTO public.archive_documents VALUES (3, 'SURAT_MASUK', 'application/pdf', false, NULL, NULL, NULL, 0, 'PROPOSAL KEGIATAN MAKRAB HIMATIF 2026.pdf', 550805, '92298d3f-82c8-4818-82bc-3c44baa95e3b.pdf', '92298d3f-82c8-4818-82bc-3c44baa95e3b.pdf', 'tes', '2026-06-22 22:19:13.244364', 'khalisha.ulfa.marsha@mailinator.com', NULL);


--
-- TOC entry 5174 (class 0 OID 66151)
-- Dependencies: 235
-- Data for Name: asset_borrowings; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5175 (class 0 OID 66171)
-- Dependencies: 236
-- Data for Name: asset_condition_histories; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5176 (class 0 OID 66188)
-- Dependencies: 237
-- Data for Name: assets; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5177 (class 0 OID 66204)
-- Dependencies: 238
-- Data for Name: cleanliness_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5178 (class 0 OID 66219)
-- Dependencies: 239
-- Data for Name: cleanliness_point_records; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5179 (class 0 OID 66236)
-- Dependencies: 240
-- Data for Name: cleanliness_schedules; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5159 (class 0 OID 57461)
-- Dependencies: 220
-- Data for Name: division_task_evidences; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.division_task_evidences VALUES (1, true, '2026-06-09 00:57:24.152961', 'Dokumentasi hasil koordinasi penyusunan jadwal pelatihan.', 'https://drive.google.com/example', NULL, 'Link dokumentasi rapat Divdik', 'LINK', '2026-06-09 00:57:24.152961', 1, NULL);


--
-- TOC entry 5161 (class 0 OID 57477)
-- Dependencies: 222
-- Data for Name: division_tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.division_tasks VALUES (1, true, '2026-06-09 00:41:52.207622', 'Menyusun jadwal materi, instruktur, dan pembagian kelas untuk pelatihan Java.', '2026-06-10', 'HIGH', 'DONE', 'Susun jadwal pelatihan Java minggu ini', '2026-06-09 00:42:45.239169', 1, 1);


--
-- TOC entry 5163 (class 0 OID 57495)
-- Dependencies: 224
-- Data for Name: divisions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.divisions VALUES (1, true, 'DIVDIK', '2026-06-07 06:45:27.110282', 'Mengelola pelatihan, kurikulum, instruktur, dan pembelajaran PUB.', 'Divisi Pendidikan dan Pelatihan', '2026-06-07 06:45:27.110282', 1, true);
INSERT INTO public.divisions VALUES (2, true, 'HUMAS', '2026-06-08 01:31:41.400479', 'Mengelola publikasi, dokumentasi, media sosial, web, dan citra PUB.', 'Hubungan Masyarakat', '2026-06-08 01:31:41.400479', 2, true);
INSERT INTO public.divisions VALUES (3, true, 'KESEJAHTERAAN', '2026-06-08 01:31:41.410482', 'Mengelola kebutuhan konsumsi, menu, dan kesejahteraan mahasiswa PUB.', 'Divisi Kesejahteraan', '2026-06-08 01:31:41.410482', 3, true);
INSERT INTO public.divisions VALUES (4, true, 'KEBERSIHAN', '2026-06-08 01:31:41.42348', 'Mengelola jadwal piket, area kebersihan, dan kedisiplinan kebersihan lingkungan.', 'Divisi Kebersihan', '2026-06-08 01:31:41.42348', 4, true);
INSERT INTO public.divisions VALUES (5, true, 'BAHASA_INGGRIS', '2026-06-08 01:31:41.431481', 'Mengelola setoran vocabulary, latihan bahasa Inggris, dan evaluasi pembelajaran bahasa.', 'Divisi Bahasa Inggris', '2026-06-08 01:31:41.431481', 5, true);
INSERT INTO public.divisions VALUES (6, true, 'KEROHANIAN', '2026-06-08 01:31:41.443497', 'Mengelola pengajian, setoran bacaan Al-Qur''an, dan pembinaan ibadah.', 'Divisi Kerohanian', '2026-06-08 01:31:41.443497', 6, true);
INSERT INTO public.divisions VALUES (7, true, 'KEASRAMAAN', '2026-06-08 01:31:41.460738', 'Mengelola kedisiplinan asrama, keberadaan mahasiswa, dan administrasi izin asrama.', 'Divisi Keasramaan', '2026-06-08 01:31:41.460738', 7, true);
INSERT INTO public.divisions VALUES (8, true, 'KESEHATAN', '2026-06-08 01:31:41.473731', 'Mengelola perhatian kesehatan, pendataan sakit, dan kebutuhan kesehatan mahasiswa PUB.', 'Divisi Kesehatan', '2026-06-08 01:31:41.473731', 8, true);
INSERT INTO public.divisions VALUES (9, true, 'PPMB', '2026-06-08 01:31:41.48876', 'Mengelola proses sosialisasi, seleksi, survei, dan penerimaan mahasiswa baru PUB.', 'Divisi PPMB', '2026-06-08 01:31:41.48876', 9, true);
INSERT INTO public.divisions VALUES (10, true, 'ASET', '2026-06-08 01:31:41.51373', 'Mengelola pendataan aset, peminjaman laptop, dan pemeriksaan kondisi barang.', 'Divisi Aset', '2026-06-08 01:31:41.51373', 10, true);
INSERT INTO public.divisions VALUES (11, true, 'PENGURUS_INTI', '2026-06-19 15:06:41.529967', 'Struktur inti PUB di luar pembagian divisi operasional.', 'Pengurus Inti', '2026-06-19 15:06:41.529967', 0, true);


--
-- TOC entry 5180 (class 0 OID 66253)
-- Dependencies: 241
-- Data for Name: english_activities; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5181 (class 0 OID 66270)
-- Dependencies: 242
-- Data for Name: english_deposits; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5165 (class 0 OID 57509)
-- Dependencies: 226
-- Data for Name: member_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.member_assignments VALUES (1, true, '2026-06-09 00:04:08.894578', 'ACTIVE', '2026-06-09 00:04:08.894578', 1, 1, 1, 2);
INSERT INTO public.member_assignments VALUES (2, true, '2026-06-19 01:15:09.225934', 'ACTIVE', '2026-06-19 01:15:09.225934', 1, 1, 1, 8);
INSERT INTO public.member_assignments VALUES (3, true, '2026-06-19 01:36:35.506335', 'ACTIVE', '2026-06-19 01:36:35.506335', 1, 2, 1, 8);
INSERT INTO public.member_assignments VALUES (4, true, '2026-06-19 15:06:42.090357', 'ACTIVE', '2026-06-19 15:06:42.090357', 11, 3, 1, 3);
INSERT INTO public.member_assignments VALUES (5, true, '2026-06-19 15:06:42.264485', 'ACTIVE', '2026-06-19 15:06:42.264485', 11, 4, 1, 4);
INSERT INTO public.member_assignments VALUES (6, true, '2026-06-19 15:06:42.447086', 'ACTIVE', '2026-06-19 15:06:42.447086', 11, 5, 1, 1);
INSERT INTO public.member_assignments VALUES (7, true, '2026-06-19 15:06:42.772342', 'ACTIVE', '2026-06-19 15:06:42.773352', 11, 6, 1, 5);
INSERT INTO public.member_assignments VALUES (8, true, '2026-06-19 15:06:42.97948', 'ACTIVE', '2026-06-19 15:06:42.97948', 11, 7, 1, 6);
INSERT INTO public.member_assignments VALUES (9, true, '2026-06-19 15:06:43.114052', 'ACTIVE', '2026-06-19 15:06:43.114052', 11, 8, 1, 7);
INSERT INTO public.member_assignments VALUES (10, true, '2026-06-19 15:06:43.265164', 'ACTIVE', '2026-06-19 15:06:43.265164', 1, 9, 1, 2);
INSERT INTO public.member_assignments VALUES (11, true, '2026-06-19 15:06:43.437728', 'ACTIVE', '2026-06-19 15:06:43.437728', 1, 10, 1, 2);
INSERT INTO public.member_assignments VALUES (12, true, '2026-06-19 15:06:43.516295', 'ACTIVE', '2026-06-19 15:06:43.516295', 1, 11, 1, 8);
INSERT INTO public.member_assignments VALUES (13, true, '2026-06-19 15:06:43.582855', 'ACTIVE', '2026-06-19 15:06:43.582855', 1, 12, 1, 5);
INSERT INTO public.member_assignments VALUES (14, true, '2026-06-19 15:06:43.726409', 'ACTIVE', '2026-06-19 15:06:43.726409', 1, 13, 1, 12);
INSERT INTO public.member_assignments VALUES (15, true, '2026-06-19 15:06:43.814971', 'ACTIVE', '2026-06-19 15:06:43.814971', 1, 14, 1, 12);
INSERT INTO public.member_assignments VALUES (16, true, '2026-06-19 15:06:43.978107', 'ACTIVE', '2026-06-19 15:06:43.978107', 1, 15, 1, 12);
INSERT INTO public.member_assignments VALUES (17, true, '2026-06-19 15:06:44.124671', 'ACTIVE', '2026-06-19 15:06:44.124671', 1, 16, 1, 12);
INSERT INTO public.member_assignments VALUES (18, true, '2026-06-19 15:06:44.20723', 'ACTIVE', '2026-06-19 15:06:44.20723', 1, 17, 1, 12);
INSERT INTO public.member_assignments VALUES (19, true, '2026-06-19 15:06:44.459969', 'ACTIVE', '2026-06-19 15:06:44.459969', 1, 18, 1, 12);
INSERT INTO public.member_assignments VALUES (20, true, '2026-06-19 15:06:44.559534', 'ACTIVE', '2026-06-19 15:06:44.559534', 1, 19, 1, 12);
INSERT INTO public.member_assignments VALUES (21, true, '2026-06-19 15:06:44.854705', 'ACTIVE', '2026-06-19 15:06:44.854705', 1, 20, 1, 12);
INSERT INTO public.member_assignments VALUES (22, true, '2026-06-19 15:06:45.022817', 'ACTIVE', '2026-06-19 15:06:45.022817', 1, 21, 1, 12);
INSERT INTO public.member_assignments VALUES (23, true, '2026-06-19 15:06:45.130378', 'ACTIVE', '2026-06-19 15:06:45.130378', 1, 22, 1, 12);
INSERT INTO public.member_assignments VALUES (24, true, '2026-06-19 15:06:45.246956', 'ACTIVE', '2026-06-19 15:06:45.246956', 5, 23, 1, 8);
INSERT INTO public.member_assignments VALUES (25, true, '2026-06-19 15:06:45.410073', 'ACTIVE', '2026-06-19 15:06:45.410073', 5, 13, 1, 12);
INSERT INTO public.member_assignments VALUES (26, true, '2026-06-19 15:06:45.77236', 'ACTIVE', '2026-06-19 15:06:45.77236', 5, 14, 1, 12);
INSERT INTO public.member_assignments VALUES (27, true, '2026-06-19 15:06:45.900931', 'ACTIVE', '2026-06-19 15:06:45.900931', 5, 24, 1, 12);
INSERT INTO public.member_assignments VALUES (28, true, '2026-06-19 15:06:45.968513', 'ACTIVE', '2026-06-19 15:06:45.968513', 5, 16, 1, 12);
INSERT INTO public.member_assignments VALUES (29, true, '2026-06-19 15:06:46.032508', 'ACTIVE', '2026-06-19 15:06:46.032508', 5, 17, 1, 12);
INSERT INTO public.member_assignments VALUES (30, true, '2026-06-19 15:06:46.126077', 'ACTIVE', '2026-06-19 15:06:46.126077', 5, 25, 1, 12);
INSERT INTO public.member_assignments VALUES (31, true, '2026-06-19 15:06:46.202636', 'ACTIVE', '2026-06-19 15:06:46.202636', 5, 18, 1, 12);
INSERT INTO public.member_assignments VALUES (32, true, '2026-06-19 15:06:46.292201', 'ACTIVE', '2026-06-19 15:06:46.292201', 5, 26, 1, 12);
INSERT INTO public.member_assignments VALUES (33, true, '2026-06-19 15:06:46.384776', 'ACTIVE', '2026-06-19 15:06:46.384776', 5, 12, 1, 12);
INSERT INTO public.member_assignments VALUES (34, true, '2026-06-19 15:06:46.431776', 'ACTIVE', '2026-06-19 15:06:46.431776', 5, 8, 1, 12);
INSERT INTO public.member_assignments VALUES (35, true, '2026-06-19 15:06:46.465328', 'ACTIVE', '2026-06-19 15:06:46.465328', 5, 22, 1, 12);
INSERT INTO public.member_assignments VALUES (36, true, '2026-06-19 15:06:46.542348', 'ACTIVE', '2026-06-19 15:06:46.542348', 5, 27, 1, 12);
INSERT INTO public.member_assignments VALUES (37, true, '2026-06-19 15:06:46.59089', 'ACTIVE', '2026-06-19 15:06:46.59089', 7, 28, 1, 8);
INSERT INTO public.member_assignments VALUES (38, true, '2026-06-19 15:06:46.643934', 'ACTIVE', '2026-06-19 15:06:46.643934', 7, 29, 1, 12);
INSERT INTO public.member_assignments VALUES (39, true, '2026-06-19 15:06:46.777072', 'ACTIVE', '2026-06-19 15:06:46.777072', 7, 30, 1, 12);
INSERT INTO public.member_assignments VALUES (40, true, '2026-06-19 15:06:46.851103', 'ACTIVE', '2026-06-19 15:06:46.851103', 7, 31, 1, 12);
INSERT INTO public.member_assignments VALUES (41, true, '2026-06-19 15:06:46.918653', 'ACTIVE', '2026-06-19 15:06:46.918653', 6, 32, 1, 8);
INSERT INTO public.member_assignments VALUES (42, true, '2026-06-19 15:06:47.003237', 'ACTIVE', '2026-06-19 15:06:47.003237', 6, 33, 1, 12);
INSERT INTO public.member_assignments VALUES (43, true, '2026-06-19 15:06:47.100799', 'ACTIVE', '2026-06-19 15:06:47.100799', 6, 19, 1, 12);
INSERT INTO public.member_assignments VALUES (44, true, '2026-06-19 15:06:47.144822', 'ACTIVE', '2026-06-19 15:06:47.144822', 6, 7, 1, 12);
INSERT INTO public.member_assignments VALUES (45, true, '2026-06-19 15:06:47.245944', 'ACTIVE', '2026-06-19 15:06:47.245944', 3, 34, 1, 8);
INSERT INTO public.member_assignments VALUES (46, true, '2026-06-19 15:06:47.328491', 'ACTIVE', '2026-06-19 15:06:47.328491', 3, 35, 1, 12);
INSERT INTO public.member_assignments VALUES (47, true, '2026-06-19 15:06:47.462624', 'ACTIVE', '2026-06-19 15:06:47.462624', 3, 36, 1, 12);
INSERT INTO public.member_assignments VALUES (48, true, '2026-06-19 15:06:47.525628', 'ACTIVE', '2026-06-19 15:06:47.526625', 3, 37, 1, 12);
INSERT INTO public.member_assignments VALUES (49, true, '2026-06-19 15:06:47.554654', 'ACTIVE', '2026-06-19 15:06:47.554654', 8, 24, 1, 8);
INSERT INTO public.member_assignments VALUES (50, true, '2026-06-19 15:06:47.593211', 'ACTIVE', '2026-06-19 15:06:47.593211', 8, 38, 1, 12);
INSERT INTO public.member_assignments VALUES (51, true, '2026-06-19 15:06:47.675775', 'ACTIVE', '2026-06-19 15:06:47.675775', 8, 21, 1, 12);
INSERT INTO public.member_assignments VALUES (52, true, '2026-06-19 15:06:47.788343', 'ACTIVE', '2026-06-19 15:06:47.788343', 8, 26, 1, 12);
INSERT INTO public.member_assignments VALUES (53, true, '2026-06-19 15:06:47.843376', 'ACTIVE', '2026-06-19 15:06:47.843376', 4, 39, 1, 8);
INSERT INTO public.member_assignments VALUES (54, true, '2026-06-19 15:06:47.915928', 'ACTIVE', '2026-06-19 15:06:47.915928', 4, 40, 1, 12);
INSERT INTO public.member_assignments VALUES (55, true, '2026-06-19 15:06:48.121098', 'ACTIVE', '2026-06-19 15:06:48.121098', 4, 41, 1, 12);
INSERT INTO public.member_assignments VALUES (56, true, '2026-06-19 15:06:48.212661', 'ACTIVE', '2026-06-19 15:06:48.212661', 4, 42, 1, 12);
INSERT INTO public.member_assignments VALUES (57, true, '2026-06-19 15:06:48.289229', 'ACTIVE', '2026-06-19 15:06:48.289229', 2, 13, 1, 8);
INSERT INTO public.member_assignments VALUES (58, true, '2026-06-19 15:06:48.489382', 'ACTIVE', '2026-06-19 15:06:48.489382', 2, 16, 1, 12);
INSERT INTO public.member_assignments VALUES (59, true, '2026-06-19 15:06:48.567941', 'ACTIVE', '2026-06-19 15:06:48.567941', 2, 22, 1, 12);
INSERT INTO public.member_assignments VALUES (60, true, '2026-06-19 15:06:48.642944', 'ACTIVE', '2026-06-19 15:06:48.642944', 2, 19, 1, 12);


--
-- TOC entry 5167 (class 0 OID 57525)
-- Dependencies: 228
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.members VALUES (2, true, 2, NULL, '2026-06-19 01:36:35.092287', 'superadmin@orchestria.local', 'Super Admin Orchestria', NULL, 'ACTIVE', NULL, '2026-06-22 23:03:42.760045', NULL, 1, NULL, NULL, true);
INSERT INTO public.members VALUES (1, true, 1, 'PUB 2025', '2026-06-08 17:32:27.831536', 'admin@mailinator.com', 'Super Admin Orchestria', '081234567890', 'ACTIVE', '2025001', '2026-06-19 01:15:08.996835', 'TI PUB 2025', 1, 'Teknik Informatika', NULL, true);
INSERT INTO public.members VALUES (3, true, NULL, 'PUB 2025', '2026-06-19 15:06:41.910215', 'abdul.hafiz.tanjung@mailinator.com', 'Abdul Hafiz Tanjung', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.05956', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (4, true, NULL, 'PUB 2025', '2026-06-19 15:06:42.199913', 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', 'Pangeran Valerensco Rivaldi Hutabarat', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.255656', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (5, true, NULL, 'PUB 2025', '2026-06-19 15:06:42.333478', 'ikram.fuadi.rambe@mailinator.com', 'Ikram Fuadi Rambe', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.362211', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (6, true, NULL, 'PUB 2025', '2026-06-19 15:06:42.593202', 'khalisha.ulfa.marsha@mailinator.com', 'Khalisha Ulfa Marsha', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.522315', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (7, true, NULL, 'PUB 2025', '2026-06-19 15:06:42.875916', 'andini.siti.nuriyanti@mailinator.com', 'Andini Siti Nuriyanti', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.606867', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (8, true, NULL, 'PUB 2025', '2026-06-19 15:06:43.050493', 'sri.rahayu.lestari@mailinator.com', 'Sri Rahayu Lestari', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.776414', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (9, true, NULL, 'PUB 2025', '2026-06-19 15:06:43.155603', 'dedy.darmawan.simanjuntak@mailinator.com', 'Dedy Darmawan Simanjuntak', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:33.898516', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (10, true, NULL, 'PUB 2025', '2026-06-19 15:06:43.341181', 'firman.suherman@mailinator.com', 'Firman Suherman', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.135621', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (11, true, 13, 'PUB 2025', '2026-06-19 15:06:43.481287', 'rickhy.ramadhan@mailinator.com', 'Rickhy Ramadhan', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.277176', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (12, true, NULL, 'PUB 2025', '2026-06-19 15:06:43.548305', 'raysha.fauziyah.andani@mailinator.com', 'Raysha Fauziyah Andani', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.343732', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (13, true, NULL, 'PUB 2025', '2026-06-19 15:06:43.658414', 'yudistira.syahputra@mailinator.com', 'Yudistira Syahputra', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.420286', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (14, true, NULL, 'PUB 2025', '2026-06-19 15:06:43.761969', 'taufik.rahman.tanjung@mailinator.com', 'Taufik Rahman Tanjung', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.464286', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (15, true, 17, 'PUB 2025', '2026-06-19 15:06:43.895535', 'izhar.harahap@mailinator.com', 'Izhar Harahap', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.552846', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (16, true, NULL, 'PUB 2025', '2026-06-19 15:06:44.007107', 'm.faiq.emil.fuadi@mailinator.com', 'M Faiq Emil Fuadi', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.643406', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (17, true, NULL, 'PUB 2025', '2026-06-19 15:06:44.159239', 'alif.rifki.pratama@mailinator.com', 'Alif Rifki Pratama', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.69142', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (18, true, NULL, 'PUB 2025', '2026-06-19 15:06:44.315819', 'dhea.firmasari@mailinator.com', 'Dhea Firmasari', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.740956', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (19, true, NULL, 'PUB 2025', '2026-06-19 15:06:44.507964', 'nabila.monica@mailinator.com', 'Nabila Monica', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:34.839513', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (20, true, NULL, 'PUB 2025', '2026-06-19 15:06:44.590533', 'ines.karlina@mailinator.com', 'Ines Karlina', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.124172', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (21, true, NULL, 'PUB 2025', '2026-06-19 15:06:44.961817', 'miftahul.jannah.harahap@mailinator.com', 'Miftahul Jannah Harahap', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.217731', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (22, true, NULL, 'PUB 2025', '2026-06-19 15:06:45.066382', 'dea.afrilia@mailinator.com', 'Dea Afrilia', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.280737', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (23, true, NULL, 'PUB 2025', '2026-06-19 15:06:45.190939', 'zaky.setiawan@mailinator.com', 'Zaky Setiawan', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.411826', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (24, true, NULL, 'PUB 2025', '2026-06-19 15:06:45.823355', 'fajar.sidik@mailinator.com', 'Fajar Sidik', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.582412', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (25, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.065074', 'alfarizi@mailinator.com', 'Alfarizi', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.718486', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (26, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.241634', 'apriliyanti@mailinator.com', 'Apriliyanti', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.80204', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (27, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.500339', 'sri.muthian@mailinator.com', 'Sri Muthian', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:35.985605', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (28, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.561893', 'muhammad.farid@mailinator.com', 'Muhammad Farid', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.129687', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (29, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.613894', 'azhar.farizi@mailinator.com', 'Azhar Farizi', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.310794', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (30, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.678487', 'ewi.lestari.harahap@mailinator.com', 'Ewi Lestari Harahap', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.372793', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (31, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.813069', 'yusri.hasanah@mailinator.com', 'Yusri Hasanah', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.410342', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (32, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.882664', 'ahmad.zaki.hosammido@mailinator.com', 'Ahmad Zaki Hosammido', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.457343', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (33, true, NULL, 'PUB 2025', '2026-06-19 15:06:46.954674', 'ade.dermawan@mailinator.com', 'Ade Dermawan', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.62544', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (34, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.182366', 'm.saroni@mailinator.com', 'M Saroni', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.826538', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (35, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.269487', 'ali.sahroji@mailinator.com', 'Ali Sahroji', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.860548', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (36, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.395059', 'sri.muthia.ningrum@mailinator.com', 'Sri Muthia Ningrum', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.888566', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (37, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.506623', 'galang.ponco.maulana@mailinator.com', 'Galang Ponco Maulana', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.917104', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (38, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.573202', 'padellan.riski@mailinator.com', 'Padellan Riski', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:36.991129', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (39, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.811344', 'm.haikal@mailinator.com', 'M Haikal', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:37.125211', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (40, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.865922', 'alfa.rizi@mailinator.com', 'Alfa Rizi', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:37.192224', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (41, true, NULL, 'PUB 2025', '2026-06-19 15:06:47.97552', 'raja.tegar.albaihaqi@mailinator.com', 'Raja Tegar Albaihaqi', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:37.261755', NULL, 99, NULL, NULL, true);
INSERT INTO public.members VALUES (42, true, NULL, 'PUB 2025', '2026-06-19 15:06:48.162658', 'ulil.arsyad.ramadhan@mailinator.com', 'Ulil Arsyad Ramadhan', NULL, 'ACTIVE', NULL, '2026-06-19 16:54:37.323309', NULL, 99, NULL, NULL, true);


--
-- TOC entry 5169 (class 0 OID 57541)
-- Dependencies: 230
-- Data for Name: organization_periods; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.organization_periods VALUES (1, '2026-06-08 01:31:41.261908', '2026-08-31', true, 'PUB 2025/2026', '2025-09-01', '2026-06-08 01:31:41.261908', true, true);
INSERT INTO public.organization_periods VALUES (2, '2026-06-08 15:06:03.267435', '2027-08-31', true, 'PUB 2026/2027', '2026-09-01', '2026-06-08 15:06:03.267435', false, true);


--
-- TOC entry 5171 (class 0 OID 57552)
-- Dependencies: 232
-- Data for Name: positions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.positions VALUES (1, true, 'KEAMANAN', '2026-06-07 06:45:49.699131', 'Bertanggung jawab atas penertiban, kedisiplinan, dan pengawasan izin keluar mahasiswa PUB.', 3, 'Keamanan', '2026-06-07 06:45:49.699131', true);
INSERT INTO public.positions VALUES (2, true, 'COACH_INSTRUKTUR', '2026-06-07 06:46:00.525136', 'Membina dan mengarahkan instruktur agar mengajar sesuai kurikulum dan standar pelatihan.', 4, 'Coach Instruktur', '2026-06-07 06:46:00.525136', true);
INSERT INTO public.positions VALUES (3, true, 'PEMBINA', '2026-06-08 01:31:41.541803', 'Pembina utama organisasi dan pengambil persetujuan akhir.', 1, 'Pembina', '2026-06-08 01:31:41.541803', true);
INSERT INTO public.positions VALUES (4, true, 'KETUA_PUB', '2026-06-08 01:31:41.557357', 'Pemimpin utama mahasiswa PUB dan penanggung jawab koordinasi organisasi.', 2, 'Ketua PUB', '2026-06-08 01:31:41.557357', true);
INSERT INTO public.positions VALUES (5, true, 'SEKRETARIS', '2026-06-08 01:31:41.573356', 'Mengelola administrasi, arsip, surat, dan dokumentasi organisasi.', 4, 'Sekretaris', '2026-06-08 01:31:41.573356', true);
INSERT INTO public.positions VALUES (6, true, 'BENDAHARA_INTERNAL', '2026-06-08 01:31:41.588359', 'Mengelola pengajuan, pencairan internal, bukti pembayaran, dan settlement.', 5, 'Bendahara Internal', '2026-06-08 01:31:41.588359', true);
INSERT INTO public.positions VALUES (7, true, 'BENDAHARA_EKSTERNAL', '2026-06-08 01:31:41.598358', 'Mencatat laporan keuangan keseluruhan dan penarikan dana dari pihak pembina/yayasan.', 6, 'Bendahara Eksternal', '2026-06-08 01:31:41.598358', true);
INSERT INTO public.positions VALUES (8, true, 'KETUA_DIVISI', '2026-06-08 01:31:41.610358', 'Memimpin dan bertanggung jawab atas operasional divisi.', 7, 'Ketua Divisi', '2026-06-08 01:31:41.610358', true);
INSERT INTO public.positions VALUES (9, true, 'KOORDINATOR_DIVISI', '2026-06-08 01:31:41.622355', 'Membantu koordinasi teknis pekerjaan divisi.', 8, 'Koordinator Divisi', '2026-06-08 01:31:41.622355', true);
INSERT INTO public.positions VALUES (10, true, 'KETUA_ASRAMA', '2026-06-08 01:31:41.63336', 'Mengelola koordinasi keasramaan dan administrasi izin asrama.', 9, 'Ketua Asrama', '2026-06-08 01:31:41.63336', true);
INSERT INTO public.positions VALUES (11, true, 'INSTRUKTUR', '2026-06-08 01:31:41.650901', 'Mengajar dan membimbing peserta pelatihan sesuai materi yang ditetapkan.', 11, 'Instruktur', '2026-06-08 01:31:41.650901', true);
INSERT INTO public.positions VALUES (12, true, 'ANGGOTA', '2026-06-08 01:31:41.6589', 'Mahasiswa PUB aktif yang mengikuti kegiatan dan kewajiban organisasi.', 99, 'Anggota', '2026-06-08 01:31:41.6589', true);


--
-- TOC entry 5182 (class 0 OID 66288)
-- Dependencies: 243
-- Data for Name: public_content_entries; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5189 (class 0 OID 0)
-- Dependencies: 233
-- Name: archive_documents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.archive_documents_id_seq', 3, true);


--
-- TOC entry 5190 (class 0 OID 0)
-- Dependencies: 219
-- Name: division_task_evidences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.division_task_evidences_id_seq', 1, true);


--
-- TOC entry 5191 (class 0 OID 0)
-- Dependencies: 221
-- Name: division_tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.division_tasks_id_seq', 1, true);


--
-- TOC entry 5192 (class 0 OID 0)
-- Dependencies: 223
-- Name: divisions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.divisions_id_seq', 11, true);


--
-- TOC entry 5193 (class 0 OID 0)
-- Dependencies: 225
-- Name: member_assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.member_assignments_id_seq', 60, true);


--
-- TOC entry 5194 (class 0 OID 0)
-- Dependencies: 227
-- Name: members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.members_id_seq', 42, true);


--
-- TOC entry 5195 (class 0 OID 0)
-- Dependencies: 229
-- Name: organization_periods_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organization_periods_id_seq', 2, true);


--
-- TOC entry 5196 (class 0 OID 0)
-- Dependencies: 231
-- Name: positions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.positions_id_seq', 12, true);


--
-- TOC entry 4978 (class 2606 OID 66107)
-- Name: archive_documents archive_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.archive_documents
    ADD CONSTRAINT archive_documents_pkey PRIMARY KEY (id);


--
-- TOC entry 4980 (class 2606 OID 66170)
-- Name: asset_borrowings asset_borrowings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_borrowings
    ADD CONSTRAINT asset_borrowings_pkey PRIMARY KEY (id);


--
-- TOC entry 4982 (class 2606 OID 66187)
-- Name: asset_condition_histories asset_condition_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_condition_histories
    ADD CONSTRAINT asset_condition_histories_pkey PRIMARY KEY (id);


--
-- TOC entry 4984 (class 2606 OID 66203)
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- TOC entry 4988 (class 2606 OID 66218)
-- Name: cleanliness_assignments cleanliness_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleanliness_assignments
    ADD CONSTRAINT cleanliness_assignments_pkey PRIMARY KEY (id);


--
-- TOC entry 4990 (class 2606 OID 66235)
-- Name: cleanliness_point_records cleanliness_point_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleanliness_point_records
    ADD CONSTRAINT cleanliness_point_records_pkey PRIMARY KEY (id);


--
-- TOC entry 4992 (class 2606 OID 66252)
-- Name: cleanliness_schedules cleanliness_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleanliness_schedules
    ADD CONSTRAINT cleanliness_schedules_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 57475)
-- Name: division_task_evidences division_task_evidences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.division_task_evidences
    ADD CONSTRAINT division_task_evidences_pkey PRIMARY KEY (id);


--
-- TOC entry 4952 (class 2606 OID 57493)
-- Name: division_tasks division_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.division_tasks
    ADD CONSTRAINT division_tasks_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 57507)
-- Name: divisions divisions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.divisions
    ADD CONSTRAINT divisions_pkey PRIMARY KEY (id);


--
-- TOC entry 4994 (class 2606 OID 66269)
-- Name: english_activities english_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.english_activities
    ADD CONSTRAINT english_activities_pkey PRIMARY KEY (id);


--
-- TOC entry 4996 (class 2606 OID 66287)
-- Name: english_deposits english_deposits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.english_deposits
    ADD CONSTRAINT english_deposits_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 57523)
-- Name: member_assignments member_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_assignments
    ADD CONSTRAINT member_assignments_pkey PRIMARY KEY (id);


--
-- TOC entry 4964 (class 2606 OID 57539)
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- TOC entry 4968 (class 2606 OID 57550)
-- Name: organization_periods organization_periods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organization_periods
    ADD CONSTRAINT organization_periods_pkey PRIMARY KEY (id);


--
-- TOC entry 4972 (class 2606 OID 57565)
-- Name: positions positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);


--
-- TOC entry 4998 (class 2606 OID 66303)
-- Name: public_content_entries public_content_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.public_content_entries
    ADD CONSTRAINT public_content_entries_pkey PRIMARY KEY (id);


--
-- TOC entry 4974 (class 2606 OID 57579)
-- Name: positions uk3vhyopdpf9huqh1t67ho6nayj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT uk3vhyopdpf9huqh1t67ho6nayj UNIQUE (name);


--
-- TOC entry 4970 (class 2606 OID 57575)
-- Name: organization_periods uk8ajhkcyi6uqql4xeqkfqvagw8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organization_periods
    ADD CONSTRAINT uk8ajhkcyi6uqql4xeqkfqvagw8 UNIQUE (name);


--
-- TOC entry 4966 (class 2606 OID 57573)
-- Name: members uk9d30a9u1qpg8eou0otgkwrp5d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT uk9d30a9u1qpg8eou0otgkwrp5d UNIQUE (email);


--
-- TOC entry 4962 (class 2606 OID 57571)
-- Name: member_assignments uk_member_period_division_position; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_assignments
    ADD CONSTRAINT uk_member_period_division_position UNIQUE (member_id, period_id, division_id, position_id);


--
-- TOC entry 4976 (class 2606 OID 57577)
-- Name: positions ukdjkia0ifarv9epmv78bh62r3o; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT ukdjkia0ifarv9epmv78bh62r3o UNIQUE (code);


--
-- TOC entry 4986 (class 2606 OID 66305)
-- Name: assets ukh3rqbypxh7aycu4jdf3sisunv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT ukh3rqbypxh7aycu4jdf3sisunv UNIQUE (asset_code);


--
-- TOC entry 4956 (class 2606 OID 57567)
-- Name: divisions ukhccml8hpwk506p2l66y8tg1ki; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.divisions
    ADD CONSTRAINT ukhccml8hpwk506p2l66y8tg1ki UNIQUE (code);


--
-- TOC entry 4958 (class 2606 OID 57569)
-- Name: divisions ukoujei63okkb767mmtbv0rrx7p; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.divisions
    ADD CONSTRAINT ukoujei63okkb767mmtbv0rrx7p UNIQUE (name);


--
-- TOC entry 5009 (class 2606 OID 66321)
-- Name: cleanliness_assignments fk19agdiahuvff5ec52qh6vj7jm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cleanliness_assignments
    ADD CONSTRAINT fk19agdiahuvff5ec52qh6vj7jm FOREIGN KEY (schedule_id) REFERENCES public.cleanliness_schedules(id);


--
-- TOC entry 5010 (class 2606 OID 66326)
-- Name: english_deposits fkbji0o62cokwcs7bhs0nm6bi6y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.english_deposits
    ADD CONSTRAINT fkbji0o62cokwcs7bhs0nm6bi6y FOREIGN KEY (activity_id) REFERENCES public.english_activities(id);


--
-- TOC entry 5002 (class 2606 OID 57600)
-- Name: member_assignments fkcxj9bp7l52xbddgns8ckekeqh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_assignments
    ADD CONSTRAINT fkcxj9bp7l52xbddgns8ckekeqh FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- TOC entry 4999 (class 2606 OID 57580)
-- Name: division_task_evidences fkdchdukb3y9tyxp4n7cstnfnl1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.division_task_evidences
    ADD CONSTRAINT fkdchdukb3y9tyxp4n7cstnfnl1 FOREIGN KEY (task_id) REFERENCES public.division_tasks(id);


--
-- TOC entry 5007 (class 2606 OID 66316)
-- Name: asset_condition_histories fkfqfcm3865mx0kwmx1x1t4jtrm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_condition_histories
    ADD CONSTRAINT fkfqfcm3865mx0kwmx1x1t4jtrm FOREIGN KEY (borrowing_id) REFERENCES public.asset_borrowings(id);


--
-- TOC entry 5000 (class 2606 OID 57585)
-- Name: division_tasks fkis7lfcy7quukggj847lwdb4bw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.division_tasks
    ADD CONSTRAINT fkis7lfcy7quukggj847lwdb4bw FOREIGN KEY (assigned_member_id) REFERENCES public.members(id);


--
-- TOC entry 5003 (class 2606 OID 57610)
-- Name: member_assignments fkj7k3clwnoxs019kfowyhp0ww1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_assignments
    ADD CONSTRAINT fkj7k3clwnoxs019kfowyhp0ww1 FOREIGN KEY (position_id) REFERENCES public.positions(id);


--
-- TOC entry 5001 (class 2606 OID 57590)
-- Name: division_tasks fkp7dvq92hfmlhci8vpcko4605; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.division_tasks
    ADD CONSTRAINT fkp7dvq92hfmlhci8vpcko4605 FOREIGN KEY (division_id) REFERENCES public.divisions(id);


--
-- TOC entry 5006 (class 2606 OID 66306)
-- Name: asset_borrowings fkroq1i3ysa7acfk3j47t5vid1r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_borrowings
    ADD CONSTRAINT fkroq1i3ysa7acfk3j47t5vid1r FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- TOC entry 5008 (class 2606 OID 66311)
-- Name: asset_condition_histories fkspvelyus68famxr3dk4ech612; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_condition_histories
    ADD CONSTRAINT fkspvelyus68famxr3dk4ech612 FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- TOC entry 5004 (class 2606 OID 57595)
-- Name: member_assignments fktbk49vw0ge14915xj08dvp7ix; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_assignments
    ADD CONSTRAINT fktbk49vw0ge14915xj08dvp7ix FOREIGN KEY (division_id) REFERENCES public.divisions(id);


--
-- TOC entry 5005 (class 2606 OID 57605)
-- Name: member_assignments fkto4onj6gmjwcw2dy4c5tcsmej; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_assignments
    ADD CONSTRAINT fkto4onj6gmjwcw2dy4c5tcsmej FOREIGN KEY (period_id) REFERENCES public.organization_periods(id);


-- Completed on 2026-06-22 23:50:43

--
-- PostgreSQL database dump complete
--

\unrestrict UFHA9R0QJYyhDSH4rQhcUjBivS8un1UNmI0F7Y5UD0lzoRTMgkWZjkFoJDpdBAB

