--
-- PostgreSQL database dump
--

\restrict 3Qsxb7o7TeM9VJ0YgJCq2VVr4daL8GVZOj40cICA91sgITKuP8mKhC4JHVJswY1

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-06-22 23:50:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5063 (class 1262 OID 57622)
-- Name: orchestria_request_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE orchestria_request_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE orchestria_request_db OWNER TO postgres;

\unrestrict 3Qsxb7o7TeM9VJ0YgJCq2VVr4daL8GVZOj40cICA91sgITKuP8mKhC4JHVJswY1
\connect orchestria_request_db
\restrict 3Qsxb7o7TeM9VJ0YgJCq2VVr4daL8GVZOj40cICA91sgITKuP8mKhC4JHVJswY1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 57624)
-- Name: fund_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fund_requests (
    id bigint NOT NULL,
    active boolean NOT NULL,
    activity_date date,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_email character varying(150) NOT NULL,
    description text,
    division_id bigint NOT NULL,
    division_name character varying(150) NOT NULL,
    priority character varying(50) NOT NULL,
    requester_auth_user_id bigint,
    requester_member_id bigint NOT NULL,
    requester_name character varying(150) NOT NULL,
    status character varying(50) NOT NULL,
    submitted_at timestamp(6) without time zone,
    title character varying(150) NOT NULL,
    total_amount numeric(18,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by_email character varying(150),
    CONSTRAINT fund_requests_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'URGENT'::character varying])::text[]))),
    CONSTRAINT fund_requests_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'DIVISION_APPROVED'::character varying, 'PUB_APPROVED'::character varying, 'PEMBINA_APPROVED'::character varying, 'REVISION_REQUESTED'::character varying, 'REJECTED'::character varying, 'READY_FOR_DISBURSEMENT'::character varying, 'DISBURSED'::character varying, 'FUND_RECEIVED'::character varying, 'SETTLEMENT_SUBMITTED'::character varying, 'SETTLEMENT_REVISION_REQUIRED'::character varying, 'SETTLEMENT_APPROVED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.fund_requests OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 57623)
-- Name: fund_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fund_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 57667)
-- Name: request_approvals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_approvals (
    id bigint NOT NULL,
    approver_email character varying(150) NOT NULL,
    approver_name character varying(150),
    decided_at timestamp(6) without time zone NOT NULL,
    decision character varying(50) NOT NULL,
    level character varying(50) NOT NULL,
    note text,
    fund_request_id bigint NOT NULL,
    CONSTRAINT request_approvals_decision_check CHECK (((decision)::text = ANY ((ARRAY['APPROVED'::character varying, 'REJECTED'::character varying, 'REVISION_REQUESTED'::character varying])::text[]))),
    CONSTRAINT request_approvals_level_check CHECK (((level)::text = ANY ((ARRAY['DIVISION'::character varying, 'PUB'::character varying, 'PEMBINA'::character varying])::text[])))
);


ALTER TABLE public.request_approvals OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 57666)
-- Name: request_approvals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_approvals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_approvals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 57646)
-- Name: request_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_items (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    item_name character varying(150) NOT NULL,
    quantity integer NOT NULL,
    subtotal numeric(18,2) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    fund_request_id bigint NOT NULL
);


ALTER TABLE public.request_items OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 57645)
-- Name: request_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 65674)
-- Name: request_settlements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_settlements (
    id bigint NOT NULL,
    active boolean NOT NULL,
    approved_at timestamp(6) without time zone,
    approved_by_email character varying(150),
    created_at timestamp(6) without time zone NOT NULL,
    note text,
    proof_url character varying(500),
    remaining_amount numeric(18,2) NOT NULL,
    shortage_amount numeric(18,2) NOT NULL,
    spent_amount numeric(18,2) NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    submitted_by_email character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone,
    fund_request_id bigint NOT NULL,
    status character varying(30),
    submission_count integer DEFAULT 1,
    revision_count integer DEFAULT 0,
    last_revision_note text,
    reviewed_by_email character varying(150),
    reviewed_at timestamp without time zone,
    lock_version bigint DEFAULT 0
);


ALTER TABLE public.request_settlements OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 65673)
-- Name: request_settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 57688)
-- Name: request_status_histories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_status_histories (
    id bigint NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    changed_by_email character varying(150) NOT NULL,
    new_status character varying(50) NOT NULL,
    note text,
    old_status character varying(50),
    fund_request_id bigint NOT NULL,
    CONSTRAINT request_status_histories_new_status_check CHECK (((new_status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'DIVISION_APPROVED'::character varying, 'PUB_APPROVED'::character varying, 'PEMBINA_APPROVED'::character varying, 'REVISION_REQUESTED'::character varying, 'REJECTED'::character varying, 'READY_FOR_DISBURSEMENT'::character varying, 'DISBURSED'::character varying, 'FUND_RECEIVED'::character varying, 'SETTLEMENT_SUBMITTED'::character varying, 'SETTLEMENT_REVISION_REQUIRED'::character varying, 'SETTLEMENT_APPROVED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT request_status_histories_old_status_check CHECK (((old_status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'DIVISION_APPROVED'::character varying, 'PUB_APPROVED'::character varying, 'PEMBINA_APPROVED'::character varying, 'REVISION_REQUESTED'::character varying, 'REJECTED'::character varying, 'READY_FOR_DISBURSEMENT'::character varying, 'DISBURSED'::character varying, 'FUND_RECEIVED'::character varying, 'SETTLEMENT_SUBMITTED'::character varying, 'SETTLEMENT_REVISION_REQUIRED'::character varying, 'SETTLEMENT_APPROVED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.request_status_histories OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 57687)
-- Name: request_status_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_status_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_status_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5049 (class 0 OID 57624)
-- Dependencies: 220
-- Data for Name: fund_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.fund_requests VALUES (6, true, '2026-06-25', '2026-06-22 23:23:17.178094', '2026-06-22 23:12:49.761347', 'izhar.harahap@mailinator.com', NULL, 1, 'Divisi Pendidikan dan Pelatihan', 'MEDIUM', 17, 15, 'Izhar Harahap', 'COMPLETED', '2026-06-22 23:16:36.779733', 'buat pengajuan', 20000.00, '2026-06-22 23:23:17.183883', 'andini.siti.nuriyanti@mailinator.com');
INSERT INTO public.fund_requests VALUES (1, true, '2026-06-10', '2026-06-16 02:54:38.085184', '2026-06-16 00:20:42.970315', 'superadmin@mailinator.com', 'Konsumsi untuk rapat koordinasi divisi', 1, 'Divisi Kesejahteraan', 'MEDIUM', 1, 1, 'Pangeran Valerensco Rivaldi Hutabarat', 'COMPLETED', '2026-06-16 00:26:19.340205', 'Pengajuan Konsumsi Rapat Divisi', 250000.00, '2026-06-16 02:54:38.088185', 'superadmin@mailinator.com');
INSERT INTO public.fund_requests VALUES (4, true, '2026-06-20', '2026-06-20 00:34:07.554095', '2026-06-19 15:43:03.725671', 'izhar.harahap@mailinator.com', 'tes flow', 1, 'Divisi Pendidikan dan Pelatihan', 'MEDIUM', 17, 15, 'Izhar Harahap', 'COMPLETED', '2026-06-19 15:46:46.412008', 'tes flow', 8000.00, '2026-06-20 00:34:07.562671', 'andini.siti.nuriyanti@mailinator.com');
INSERT INTO public.fund_requests VALUES (5, true, '2026-06-20', NULL, '2026-06-20 17:33:13.077279', 'rickhy.ramadhan@mailinator.com', 'im broke nigga', 1, 'Divisi Pendidikan dan Pelatihan', 'HIGH', 13, 11, 'Rickhy Ramadhan', 'DRAFT', NULL, 'Gaji Koordinator', 0.00, '2026-06-20 17:33:13.077279', 'rickhy.ramadhan@mailinator.com');
INSERT INTO public.fund_requests VALUES (3, true, '2026-10-10', NULL, '2026-06-19 13:37:06.375399', 'superadmin@mailinator.com', 'sese', 1, 'Divisi Pendidikan dan Pelatihan', 'MEDIUM', 2, 2, 'Super Admin Orchestria', 'REVISION_REQUESTED', '2026-06-19 13:37:32.502061', 'tesss', 2000.00, '2026-06-19 13:37:59.679795', 'superadmin@mailinator.com');
INSERT INTO public.fund_requests VALUES (2, true, NULL, NULL, '2026-06-19 01:42:07.873727', 'superadmin@mailinator.com', NULL, 1, 'Divisi Pendidikan dan Pelatihan', 'MEDIUM', 2, 2, 'Super Admin Orchestria', 'READY_FOR_DISBURSEMENT', '2026-06-19 02:24:28.777637', 'Konsumsi Pelatihan Java', 55000.00, '2026-06-19 13:38:09.429082', 'superadmin@mailinator.com');


--
-- TOC entry 5053 (class 0 OID 57667)
-- Dependencies: 224
-- Data for Name: request_approvals; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.request_approvals VALUES (1, 'superadmin@mailinator.com', 'Ketua Divisi Kesejahteraan', '2026-06-16 00:40:12.537283', 'APPROVED', 'DIVISION', 'Disetujui oleh Divisi', 1);
INSERT INTO public.request_approvals VALUES (2, 'superadmin@mailinator.com', 'Ketua Divisi Kesejahteraan', '2026-06-16 00:41:49.840003', 'APPROVED', 'PUB', 'Disetujui Ketua PUB', 1);
INSERT INTO public.request_approvals VALUES (3, 'superadmin@mailinator.com', 'Abdul Hafiz Tanjung', '2026-06-16 00:42:19.703512', 'APPROVED', 'PEMBINA', 'Disetujui Pembina', 1);
INSERT INTO public.request_approvals VALUES (4, 'superadmin@mailinator.com', 'Super Admin Orchestria', '2026-06-19 09:54:44.444873', 'APPROVED', 'DIVISION', 'oke', 2);
INSERT INTO public.request_approvals VALUES (5, 'superadmin@mailinator.com', 'Super Admin Orchestria', '2026-06-19 13:37:45.275022', 'APPROVED', 'DIVISION', 'aman', 3);
INSERT INTO public.request_approvals VALUES (6, 'superadmin@mailinator.com', 'Super Admin Orchestria', '2026-06-19 13:37:50.735743', 'APPROVED', 'PUB', 'asas', 2);
INSERT INTO public.request_approvals VALUES (7, 'superadmin@mailinator.com', 'Super Admin Orchestria', '2026-06-19 13:37:59.606368', 'REVISION_REQUESTED', 'PUB', 'ini ga mantap', 3);
INSERT INTO public.request_approvals VALUES (8, 'superadmin@mailinator.com', 'Super Admin Orchestria', '2026-06-19 13:38:09.256902', 'APPROVED', 'PEMBINA', 'ok', 2);
INSERT INTO public.request_approvals VALUES (9, 'rickhy.ramadhan@mailinator.com', 'Rickhy Ramadhan', '2026-06-19 15:47:26.394335', 'APPROVED', 'DIVISION', 'mntp', 4);
INSERT INTO public.request_approvals VALUES (10, 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', 'Pangeran Valerensco Rivaldi Hutabarat', '2026-06-19 15:49:05.600615', 'APPROVED', 'PUB', 'oke', 4);
INSERT INTO public.request_approvals VALUES (11, 'abdul.hafiz.tanjung@mailinator.com', 'Abdul Hafiz Tanjung', '2026-06-19 15:50:06.733743', 'APPROVED', 'PEMBINA', 'as', 4);
INSERT INTO public.request_approvals VALUES (12, 'rickhy.ramadhan@mailinator.com', 'Rickhy Ramadhan', '2026-06-22 23:17:03.319347', 'APPROVED', 'DIVISION', 'ok', 6);
INSERT INTO public.request_approvals VALUES (13, 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', 'Pangeran Valerensco Rivaldi Hutabarat', '2026-06-22 23:17:56.513627', 'APPROVED', 'PUB', 'ok', 6);
INSERT INTO public.request_approvals VALUES (14, 'abdul.hafiz.tanjung@mailinator.com', 'Abdul Hafiz Tanjung', '2026-06-22 23:20:04.018575', 'APPROVED', 'PEMBINA', 'ok', 6);


--
-- TOC entry 5051 (class 0 OID 57646)
-- Dependencies: 222
-- Data for Name: request_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.request_items VALUES (1, true, '2026-06-16 00:21:11.376033', 'Konsumsi peserta rapat', 'Nasi Box', 10, 250000.00, 25000.00, '2026-06-16 00:21:11.376033', 1);
INSERT INTO public.request_items VALUES (2, true, '2026-06-19 02:22:53.56584', 'Konsumsi Pelatihan', 'Konsumsi Peserta', 10, 25000.00, 2500.00, '2026-06-19 02:22:53.56584', 2);
INSERT INTO public.request_items VALUES (3, true, '2026-06-19 02:24:16.223484', '121', 'tres', 1, 30000.00, 30000.00, '2026-06-19 02:24:16.223484', 2);
INSERT INTO public.request_items VALUES (4, true, '2026-06-19 13:37:28.483489', 'asa', 'sasa', 1, 2000.00, 2000.00, '2026-06-19 13:37:28.483489', 3);
INSERT INTO public.request_items VALUES (5, true, '2026-06-19 15:46:41.88218', 'asa', 'kue', 2, 8000.00, 4000.00, '2026-06-19 15:46:41.88218', 4);
INSERT INTO public.request_items VALUES (6, true, '2026-06-22 23:16:33.404623', NULL, 'tesss', 1, 20000.00, 20000.00, '2026-06-22 23:16:33.404623', 6);


--
-- TOC entry 5057 (class 0 OID 65674)
-- Dependencies: 228
-- Data for Name: request_settlements; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.request_settlements VALUES (1, true, '2026-06-16 02:54:38.084185', 'superadmin@mailinator.com', '2026-06-16 02:53:52.049666', 'Dana digunakan untuk konsumsi rapat, sisa 10000', 'https://example.com/struk.jpg', 10000.00, 0.00, 240000.00, '2026-06-16 02:53:52.049666', 'superadmin@mailinator.com', '2026-06-16 02:54:38.088185', 1, NULL, 1, 0, NULL, NULL, NULL, 0);
INSERT INTO public.request_settlements VALUES (2, true, '2026-06-20 00:34:07.554095', 'andini.siti.nuriyanti@mailinator.com', '2026-06-19 16:22:53.029678', 'Laporan diperbaiki dan bukti penggunaan dilampirkan.', 'https://drive.google.com/contoh-bukti', 0.01, 0.00, 7999.99, '2026-06-20 00:33:50.630788', 'izhar.harahap@mailinator.com', '2026-06-20 00:34:07.56367', 4, 'APPROVED', 3, 2, 'manaaa?', 'andini.siti.nuriyanti@mailinator.com', '2026-06-20 00:34:07.554095', 4);
INSERT INTO public.request_settlements VALUES (3, true, '2026-06-22 23:23:17.178094', 'andini.siti.nuriyanti@mailinator.com', '2026-06-22 23:22:15.04751', NULL, 'https://drive.google.com/test', 0.00, 0.00, 20000.00, '2026-06-22 23:22:15.043499', 'izhar.harahap@mailinator.com', '2026-06-22 23:23:17.183883', 6, 'APPROVED', 1, 0, NULL, 'andini.siti.nuriyanti@mailinator.com', '2026-06-22 23:23:17.178094', 1);


--
-- TOC entry 5055 (class 0 OID 57688)
-- Dependencies: 226
-- Data for Name: request_status_histories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.request_status_histories VALUES (1, '2026-06-16 00:26:19.341207', 'superadmin@mailinator.com', 'SUBMITTED', 'Pengajuan dana disubmit', 'DRAFT', 1);
INSERT INTO public.request_status_histories VALUES (2, '2026-06-16 00:40:12.587311', 'superadmin@mailinator.com', 'DIVISION_APPROVED', 'Pengajuan disetujui pada level DIVISION', 'SUBMITTED', 1);
INSERT INTO public.request_status_histories VALUES (3, '2026-06-16 00:41:49.844007', 'superadmin@mailinator.com', 'PUB_APPROVED', 'Pengajuan disetujui pada level PUB', 'DIVISION_APPROVED', 1);
INSERT INTO public.request_status_histories VALUES (4, '2026-06-16 00:42:19.710503', 'superadmin@mailinator.com', 'READY_FOR_DISBURSEMENT', 'Pengajuan disetujui pada level PEMBINA', 'PUB_APPROVED', 1);
INSERT INTO public.request_status_histories VALUES (5, '2026-06-16 02:29:42.203349', 'superadmin@mailinator.com', 'DISBURSED', 'Dana pengajuan sudah dicairkan oleh finance-service', 'READY_FOR_DISBURSEMENT', 1);
INSERT INTO public.request_status_histories VALUES (6, '2026-06-16 02:53:22.31189', 'superadmin@mailinator.com', 'FUND_RECEIVED', 'Dana pengajuan sudah dikonfirmasi diterima', 'DISBURSED', 1);
INSERT INTO public.request_status_histories VALUES (7, '2026-06-16 02:53:52.055665', 'superadmin@mailinator.com', 'SETTLEMENT_SUBMITTED', 'Settlement penggunaan dana dikirim', 'FUND_RECEIVED', 1);
INSERT INTO public.request_status_histories VALUES (8, '2026-06-16 02:54:38.085184', 'superadmin@mailinator.com', 'COMPLETED', 'Settlement disetujui dan pengajuan selesai', 'SETTLEMENT_SUBMITTED', 1);
INSERT INTO public.request_status_histories VALUES (9, '2026-06-19 02:24:28.779638', 'superadmin@mailinator.com', 'SUBMITTED', 'Pengajuan dana disubmit', 'DRAFT', 2);
INSERT INTO public.request_status_histories VALUES (10, '2026-06-19 09:54:44.890699', 'superadmin@mailinator.com', 'DIVISION_APPROVED', 'Pengajuan disetujui pada level DIVISION', 'SUBMITTED', 2);
INSERT INTO public.request_status_histories VALUES (11, '2026-06-19 13:37:32.511598', 'superadmin@mailinator.com', 'SUBMITTED', 'Pengajuan dana disubmit', 'DRAFT', 3);
INSERT INTO public.request_status_histories VALUES (12, '2026-06-19 13:37:45.291582', 'superadmin@mailinator.com', 'DIVISION_APPROVED', 'Pengajuan disetujui pada level DIVISION', 'SUBMITTED', 3);
INSERT INTO public.request_status_histories VALUES (13, '2026-06-19 13:37:50.949108', 'superadmin@mailinator.com', 'PUB_APPROVED', 'Pengajuan disetujui pada level PUB', 'DIVISION_APPROVED', 2);
INSERT INTO public.request_status_histories VALUES (14, '2026-06-19 13:37:59.62746', 'superadmin@mailinator.com', 'REVISION_REQUESTED', 'ini ga mantap', 'DIVISION_APPROVED', 3);
INSERT INTO public.request_status_histories VALUES (15, '2026-06-19 13:38:09.324752', 'superadmin@mailinator.com', 'READY_FOR_DISBURSEMENT', 'Pengajuan disetujui pada level PEMBINA', 'PUB_APPROVED', 2);
INSERT INTO public.request_status_histories VALUES (16, '2026-06-19 15:46:46.417007', 'izhar.harahap@mailinator.com', 'SUBMITTED', 'Pengajuan dana disubmit', 'DRAFT', 4);
INSERT INTO public.request_status_histories VALUES (17, '2026-06-19 15:47:26.409338', 'rickhy.ramadhan@mailinator.com', 'DIVISION_APPROVED', 'Pengajuan disetujui pada level DIVISION', 'SUBMITTED', 4);
INSERT INTO public.request_status_histories VALUES (18, '2026-06-19 15:49:05.644191', 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', 'PUB_APPROVED', 'Pengajuan disetujui pada level PUB', 'DIVISION_APPROVED', 4);
INSERT INTO public.request_status_histories VALUES (19, '2026-06-19 15:50:06.749269', 'abdul.hafiz.tanjung@mailinator.com', 'READY_FOR_DISBURSEMENT', 'Pengajuan disetujui pada level PEMBINA', 'PUB_APPROVED', 4);
INSERT INTO public.request_status_histories VALUES (20, '2026-06-19 15:52:23.059672', 'andini.siti.nuriyanti@mailinator.com', 'DISBURSED', 'Dana pengajuan sudah dicairkan oleh finance-service', 'READY_FOR_DISBURSEMENT', 4);
INSERT INTO public.request_status_histories VALUES (21, '2026-06-19 16:22:43.265896', 'izhar.harahap@mailinator.com', 'FUND_RECEIVED', 'Dana pengajuan sudah dikonfirmasi diterima', 'DISBURSED', 4);
INSERT INTO public.request_status_histories VALUES (22, '2026-06-19 16:22:53.071674', 'izhar.harahap@mailinator.com', 'SETTLEMENT_SUBMITTED', 'Settlement penggunaan dana dikirim', 'FUND_RECEIVED', 4);
INSERT INTO public.request_status_histories VALUES (25, '2026-06-19 23:43:58.275525', 'izhar.harahap@mailinator.com', 'SETTLEMENT_SUBMITTED', 'Settlement penggunaan dana diperbaiki dan dikirim ulang', 'SETTLEMENT_REVISION_REQUIRED', 4);
INSERT INTO public.request_status_histories VALUES (26, '2026-06-20 00:33:36.664102', 'andini.siti.nuriyanti@mailinator.com', 'SETTLEMENT_REVISION_REQUIRED', 'Settlement membutuhkan revisi: manaaa?', 'SETTLEMENT_SUBMITTED', 4);
INSERT INTO public.request_status_histories VALUES (27, '2026-06-20 00:33:50.631785', 'izhar.harahap@mailinator.com', 'SETTLEMENT_SUBMITTED', 'Settlement penggunaan dana diperbaiki dan dikirim ulang', 'SETTLEMENT_REVISION_REQUIRED', 4);
INSERT INTO public.request_status_histories VALUES (28, '2026-06-20 00:34:07.555642', 'andini.siti.nuriyanti@mailinator.com', 'COMPLETED', 'Settlement disetujui dan pengajuan selesai', 'SETTLEMENT_SUBMITTED', 4);
INSERT INTO public.request_status_histories VALUES (29, '2026-06-22 23:16:36.782271', 'izhar.harahap@mailinator.com', 'SUBMITTED', 'Pengajuan dana disubmit', 'DRAFT', 6);
INSERT INTO public.request_status_histories VALUES (30, '2026-06-22 23:17:03.325072', 'rickhy.ramadhan@mailinator.com', 'DIVISION_APPROVED', 'Pengajuan disetujui pada level DIVISION', 'SUBMITTED', 6);
INSERT INTO public.request_status_histories VALUES (31, '2026-06-22 23:17:56.517613', 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', 'PUB_APPROVED', 'Pengajuan disetujui pada level PUB', 'DIVISION_APPROVED', 6);
INSERT INTO public.request_status_histories VALUES (32, '2026-06-22 23:20:04.023574', 'abdul.hafiz.tanjung@mailinator.com', 'READY_FOR_DISBURSEMENT', 'Pengajuan disetujui pada level PEMBINA', 'PUB_APPROVED', 6);
INSERT INTO public.request_status_histories VALUES (33, '2026-06-22 23:21:22.227479', 'andini.siti.nuriyanti@mailinator.com', 'DISBURSED', 'Dana pengajuan sudah dicairkan oleh finance-service', 'READY_FOR_DISBURSEMENT', 6);
INSERT INTO public.request_status_histories VALUES (34, '2026-06-22 23:21:53.385807', 'izhar.harahap@mailinator.com', 'FUND_RECEIVED', 'Dana pengajuan sudah dikonfirmasi diterima', 'DISBURSED', 6);
INSERT INTO public.request_status_histories VALUES (35, '2026-06-22 23:22:15.054514', 'izhar.harahap@mailinator.com', 'SETTLEMENT_SUBMITTED', 'Settlement penggunaan dana dikirim', 'FUND_RECEIVED', 6);
INSERT INTO public.request_status_histories VALUES (36, '2026-06-22 23:23:17.179094', 'andini.siti.nuriyanti@mailinator.com', 'COMPLETED', 'Settlement disetujui dan pengajuan selesai', 'SETTLEMENT_SUBMITTED', 6);


--
-- TOC entry 5064 (class 0 OID 0)
-- Dependencies: 219
-- Name: fund_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fund_requests_id_seq', 6, true);


--
-- TOC entry 5065 (class 0 OID 0)
-- Dependencies: 223
-- Name: request_approvals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_approvals_id_seq', 14, true);


--
-- TOC entry 5066 (class 0 OID 0)
-- Dependencies: 221
-- Name: request_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_items_id_seq', 6, true);


--
-- TOC entry 5067 (class 0 OID 0)
-- Dependencies: 227
-- Name: request_settlements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_settlements_id_seq', 3, true);


--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 225
-- Name: request_status_histories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_status_histories_id_seq', 36, true);


--
-- TOC entry 4886 (class 2606 OID 57644)
-- Name: fund_requests fund_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fund_requests
    ADD CONSTRAINT fund_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 57681)
-- Name: request_approvals request_approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_approvals
    ADD CONSTRAINT request_approvals_pkey PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 57660)
-- Name: request_items request_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_items
    ADD CONSTRAINT request_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4894 (class 2606 OID 65689)
-- Name: request_settlements request_settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_settlements
    ADD CONSTRAINT request_settlements_pkey PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 57701)
-- Name: request_status_histories request_status_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_histories
    ADD CONSTRAINT request_status_histories_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 65691)
-- Name: request_settlements uk43nd97ey9ku4mpgyena8h74n7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_settlements
    ADD CONSTRAINT uk43nd97ey9ku4mpgyena8h74n7 UNIQUE (fund_request_id);


--
-- TOC entry 4900 (class 2606 OID 65692)
-- Name: request_settlements fk5e2o5wfidw5d3tgq3oc1vnf3t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_settlements
    ADD CONSTRAINT fk5e2o5wfidw5d3tgq3oc1vnf3t FOREIGN KEY (fund_request_id) REFERENCES public.fund_requests(id);


--
-- TOC entry 4899 (class 2606 OID 57702)
-- Name: request_status_histories fkkcekygtcdtp7t5fqaopk7rhg7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_histories
    ADD CONSTRAINT fkkcekygtcdtp7t5fqaopk7rhg7 FOREIGN KEY (fund_request_id) REFERENCES public.fund_requests(id);


--
-- TOC entry 4897 (class 2606 OID 57661)
-- Name: request_items fkqw8r1rhqugy1v8l3hxgjlxst9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_items
    ADD CONSTRAINT fkqw8r1rhqugy1v8l3hxgjlxst9 FOREIGN KEY (fund_request_id) REFERENCES public.fund_requests(id);


--
-- TOC entry 4898 (class 2606 OID 57682)
-- Name: request_approvals fksof4q841pltwt93p6wac19577; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_approvals
    ADD CONSTRAINT fksof4q841pltwt93p6wac19577 FOREIGN KEY (fund_request_id) REFERENCES public.fund_requests(id);


-- Completed on 2026-06-22 23:50:54

--
-- PostgreSQL database dump complete
--

\unrestrict 3Qsxb7o7TeM9VJ0YgJCq2VVr4daL8GVZOj40cICA91sgITKuP8mKhC4JHVJswY1

