--
-- PostgreSQL database dump
--

\restrict B1cSmFV3jxMZIkhUAhIDaCWHeJs0FnJSK7hHa2FsE5c6T7JQ7Xe5IfaGqJrwjmh

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-06-22 23:50:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5018 (class 1262 OID 65648)
-- Name: orchestria_finance_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE orchestria_finance_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE orchestria_finance_db OWNER TO postgres;

\unrestrict B1cSmFV3jxMZIkhUAhIDaCWHeJs0FnJSK7hHa2FsE5c6T7JQ7Xe5IfaGqJrwjmh
\connect orchestria_finance_db
\restrict B1cSmFV3jxMZIkhUAhIDaCWHeJs0FnJSK7hHa2FsE5c6T7JQ7Xe5IfaGqJrwjmh

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 65650)
-- Name: fund_disbursements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fund_disbursements (
    id bigint NOT NULL,
    active boolean NOT NULL,
    amount numeric(18,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    disbursed_at timestamp(6) without time zone NOT NULL,
    disbursed_by_email character varying(150) NOT NULL,
    division_id bigint NOT NULL,
    division_name character varying(150) NOT NULL,
    fund_request_id bigint NOT NULL,
    method character varying(50) NOT NULL,
    note text,
    proof_url character varying(500),
    receiver_name character varying(150) NOT NULL,
    receiver_note text,
    request_title character varying(150) NOT NULL,
    requester_name character varying(150) NOT NULL,
    status character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    request_sync_error character varying(500),
    request_synced_at timestamp(6) without time zone,
    request_sync_status character varying(30) DEFAULT 'PENDING'::character varying NOT NULL,
    request_sync_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT fund_disbursements_method_check CHECK (((method)::text = ANY ((ARRAY['CASH'::character varying, 'BANK_TRANSFER'::character varying, 'E_WALLET'::character varying])::text[]))),
    CONSTRAINT fund_disbursements_status_check CHECK (((status)::text = ANY ((ARRAY['DISBURSED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.fund_disbursements OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 65649)
-- Name: fund_disbursements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fund_disbursements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_disbursements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5012 (class 0 OID 65650)
-- Dependencies: 220
-- Data for Name: fund_disbursements; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.fund_disbursements VALUES (1, true, 250000.00, '2026-06-16 02:26:53.180219', '2026-06-16 02:26:53.180219', 'superadmin@mailinator.com', 1, 'Divisi Kesejahteraan', 1, 'CASH', 'Pencairan dana konsumsi rapat', 'https://example.com/proof.jpg', 'Pangeran Valerensco Rivaldi Hutabarat', 'Dana diterima langsung oleh pengaju', 'Pengajuan Konsumsi Rapat Divisi', 'Pangeran Valerensco Rivaldi Hutabarat', 'DISBURSED', '2026-06-16 02:26:53.180219', NULL, NULL, 'SYNCED', 0);
INSERT INTO public.fund_disbursements VALUES (2, true, 8000.00, '2026-06-19 15:52:22.500288', '2026-06-19 15:52:22.500288', 'andini.siti.nuriyanti@mailinator.com', 1, 'Divisi Pendidikan dan Pelatihan', 4, 'BANK_TRANSFER', 'pencairan core flow', NULL, 'Izhar Harahap', '02102012012010010', 'tes flow', 'Izhar Harahap', 'DISBURSED', '2026-06-19 15:52:23.142226', NULL, '2026-06-19 15:52:23.117674', 'SYNCED', 1);
INSERT INTO public.fund_disbursements VALUES (3, true, 20000.00, '2026-06-22 23:21:21.8877', '2026-06-22 23:21:21.8877', 'andini.siti.nuriyanti@mailinator.com', 1, 'Divisi Pendidikan dan Pelatihan', 6, 'BANK_TRANSFER', NULL, NULL, 'Izhar Harahap', NULL, 'buat pengajuan', 'Izhar Harahap', 'DISBURSED', '2026-06-22 23:21:22.278519', NULL, '2026-06-22 23:21:22.269522', 'SYNCED', 1);


--
-- TOC entry 5019 (class 0 OID 0)
-- Dependencies: 219
-- Name: fund_disbursements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fund_disbursements_id_seq', 3, true);


--
-- TOC entry 4861 (class 2606 OID 65672)
-- Name: fund_disbursements fund_disbursements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fund_disbursements
    ADD CONSTRAINT fund_disbursements_pkey PRIMARY KEY (id);


--
-- TOC entry 4863 (class 2606 OID 65701)
-- Name: fund_disbursements uk_fund_disbursement_request; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fund_disbursements
    ADD CONSTRAINT uk_fund_disbursement_request UNIQUE (fund_request_id);


-- Completed on 2026-06-22 23:50:17

--
-- PostgreSQL database dump complete
--

\unrestrict B1cSmFV3jxMZIkhUAhIDaCWHeJs0FnJSK7hHa2FsE5c6T7JQ7Xe5IfaGqJrwjmh

