--
-- PostgreSQL database dump
--

\restrict rAGOv74VSDWPdUGydPLiCRgZAgdLwS379TzjfzBg1MIz7wxTsS5BY7myHSPtJKd

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-06-22 23:50:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5079 (class 1262 OID 41073)
-- Name: orchestria_auth_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE orchestria_auth_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Indonesia.1252';


ALTER DATABASE orchestria_auth_db OWNER TO postgres;

\unrestrict rAGOv74VSDWPdUGydPLiCRgZAgdLwS379TzjfzBg1MIz7wxTsS5BY7myHSPtJKd
\connect orchestria_auth_db
\restrict rAGOv74VSDWPdUGydPLiCRgZAgdLwS379TzjfzBg1MIz7wxTsS5BY7myHSPtJKd

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 66108)
-- Name: otp_challenges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_challenges (
    id character varying(36) NOT NULL,
    attempt_count integer NOT NULL,
    code_hash character varying(255) NOT NULL,
    consumed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    max_attempts integer NOT NULL,
    purpose character varying(30) NOT NULL,
    resend_available_at timestamp(6) without time zone NOT NULL,
    resend_count integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT otp_challenges_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['LOGIN'::character varying, 'FORGOT_PASSWORD'::character varying, 'ENABLE_2FA'::character varying, 'DISABLE_2FA'::character varying])::text[])))
);


ALTER TABLE public.otp_challenges OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 66125)
-- Name: password_reset_grants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_grants (
    id character varying(36) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    used_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_grants OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 49265)
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 49264)
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 49274)
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 49282)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 49281)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 66135)
-- Name: trusted_devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trusted_devices (
    id character varying(36) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    device_name character varying(255),
    expires_at timestamp(6) without time zone NOT NULL,
    last_ip_address character varying(45),
    last_used_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    token_hash character varying(64) NOT NULL,
    user_agent character varying(500),
    user_id bigint NOT NULL
);


ALTER TABLE public.trusted_devices OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 49292)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 49300)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    two_factor_enabled boolean DEFAULT false NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 49299)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5071 (class 0 OID 66108)
-- Dependencies: 227
-- Data for Name: otp_challenges; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.otp_challenges VALUES ('5063121b-3991-4e80-9847-b562a4db2a9f', 0, '$2a$10$irn2t/BUvqnV8ObzVG0pQepWmS4X46EyZ/eYkdjb0rM4faap9DQMm', '2026-06-22 21:07:45.703837', '2026-06-22 21:07:10.177374', '2026-06-22 21:12:10.177374', 5, 'ENABLE_2FA', '2026-06-22 21:08:10.177374', 0, '2026-06-22 21:07:10.177374', 12);
INSERT INTO public.otp_challenges VALUES ('0ad8cb18-48dd-4d87-a845-d178ecba9277', 0, '$2a$10$bVxPokUtsdyO0i1V213vt.HJKJMrsVc1QYOX9U34mNqp139pDjpMq', '2026-06-22 21:07:45.703837', '2026-06-22 21:07:13.577757', '2026-06-22 21:12:13.577757', 5, 'ENABLE_2FA', '2026-06-22 21:08:13.577757', 0, '2026-06-22 21:07:13.577757', 12);
INSERT INTO public.otp_challenges VALUES ('53464ba2-4d59-4a5c-b670-9ba2b50b86e1', 0, '$2a$10$EP1Jnq2.ziZdORaoO1L1KOED0DOO5TfgaztlFNnL6GksfFKs0Ev8.', '2026-06-22 21:07:49.18403', '2026-06-22 21:07:45.853098', '2026-06-22 21:12:45.853098', 5, 'ENABLE_2FA', '2026-06-22 21:08:45.853098', 0, '2026-06-22 21:07:45.853098', 12);
INSERT INTO public.otp_challenges VALUES ('ce841961-b467-4efb-85ac-f78356ecf959', 0, '$2a$10$jozMiyFghAunQIbZ764OyeESMtOomErlVCgzj8U9MTCVbIWCnutGC', NULL, '2026-06-22 21:07:49.301487', '2026-06-22 21:12:49.301487', 5, 'ENABLE_2FA', '2026-06-22 21:08:49.301487', 0, '2026-06-22 21:07:49.301487', 12);
INSERT INTO public.otp_challenges VALUES ('14fb6395-f639-4cd9-81c3-2eaefc7901c3', 0, '$2a$10$ihT3pFGNq8O0wVdt4Wjz5.200UNZYpGLjqfvsmXoUbrXvmtqMvtpS', NULL, '2026-06-22 21:07:49.377973', '2026-06-22 21:12:49.377973', 5, 'ENABLE_2FA', '2026-06-22 21:08:49.377973', 0, '2026-06-22 21:07:49.377973', 12);
INSERT INTO public.otp_challenges VALUES ('80612ccd-40a1-4bbf-8231-1f188e69f0a0', 0, '$2a$10$v8w8HlbOEUPbwznvdvddqeLvqtApIgo.zAs6fYV2ofQawgELlcjpq', '2026-06-22 21:08:59.332948', '2026-06-22 20:58:39.611726', '2026-06-22 21:03:39.611726', 5, 'LOGIN', '2026-06-22 20:59:39.611726', 0, '2026-06-22 20:58:39.611726', 6);
INSERT INTO public.otp_challenges VALUES ('926b0cc2-93a9-4583-a895-304fc20332d6', 0, '$2a$10$bDoyb.yY905wsTPxvTPu2enE0i5zHjzfIOo0q1/p.uyNG/OL5otQ6', '2026-06-22 21:10:15.991169', '2026-06-22 21:08:59.506608', '2026-06-22 21:13:59.506608', 5, 'LOGIN', '2026-06-22 21:09:59.506608', 0, '2026-06-22 21:10:16.000194', 6);
INSERT INTO public.otp_challenges VALUES ('1efdf47d-aabf-4bd9-bbd3-e421ed218828', 0, '$2a$10$R1wB0BM4xFkYEcEFIkGzW.ufV0XsCII0fbtIgPdL6yyf92CdTJm8G', '2026-06-22 21:19:58.922272', '2026-06-22 21:19:35.341333', '2026-06-22 21:24:35.341333', 5, 'FORGOT_PASSWORD', '2026-06-22 21:20:35.341333', 0, '2026-06-22 21:19:58.931277', 1);
INSERT INTO public.otp_challenges VALUES ('8ab19ab8-5de6-4ce7-9228-6af850df5615', 0, '$2a$10$f8N4dmt5FBAq4VJWXMrLNeZkXvvEk1RIF5DVJb9TFzD0eYND6AOPe', '2026-06-22 22:15:19.328664', '2026-06-22 22:14:34.901324', '2026-06-22 22:19:34.901324', 5, 'FORGOT_PASSWORD', '2026-06-22 22:15:34.901324', 0, '2026-06-22 22:14:34.901324', 4);
INSERT INTO public.otp_challenges VALUES ('6663f799-7ac0-4989-aead-eb7e5817987c', 0, '$2a$10$0jpb4rWjs0MhKEM.dEBMDe.zGlxBAX.o.U4cBWDd3Ap70gb7r9NWO', NULL, '2026-06-22 22:15:19.581008', '2026-06-22 22:20:19.581008', 5, 'FORGOT_PASSWORD', '2026-06-22 22:16:19.581008', 0, '2026-06-22 22:15:19.581008', 4);
INSERT INTO public.otp_challenges VALUES ('ee969276-0f23-4145-89e9-7a5d6ec56f7d', 0, '$2a$10$QQ.katoSx0gHz8kjT3kw..6QC6ZZ0g09SWaK4d5VUp2vVAnaU19IO', '2026-06-22 22:16:02.389259', '2026-06-22 22:15:46.119219', '2026-06-22 22:20:46.119219', 5, 'FORGOT_PASSWORD', '2026-06-22 22:16:46.119219', 0, '2026-06-22 22:16:02.396273', 17);
INSERT INTO public.otp_challenges VALUES ('8e7d53bd-1767-418e-b61b-29bda0dcf67d', 0, '$2a$10$2U/3XvbHMZotFIEkcQRO4.97wzR6K9xlQJYl/SLoEy3Gg45EQESg.', NULL, '2026-06-22 22:16:43.613341', '2026-06-22 22:21:43.613341', 5, 'ENABLE_2FA', '2026-06-22 22:17:43.613341', 0, '2026-06-22 22:16:43.613341', 17);
INSERT INTO public.otp_challenges VALUES ('ccf2f039-9678-4827-8152-77c79392575f', 0, '$2a$10$7mKqoxGgHpCw93FGLw6kZ.4gfmbGD4PqMEPidC2G8dNW2HZSb0/l.', '2026-06-22 22:17:03.340621', '2026-06-22 22:16:46.14324', '2026-06-22 22:21:46.14324', 5, 'ENABLE_2FA', '2026-06-22 22:17:46.14324', 0, '2026-06-22 22:17:03.343627', 17);
INSERT INTO public.otp_challenges VALUES ('20911495-96f1-43d8-bdf0-ab9bc4af2d27', 0, '$2a$10$BSfjXd98F.g9n48vWawycesC3Kc8fiKk5Fgp9KRcGYHv36b7KFbRa', '2026-06-22 22:25:50.209935', '2026-06-22 21:20:14.826298', '2026-06-22 21:25:14.826298', 5, 'LOGIN', '2026-06-22 21:21:14.826298', 0, '2026-06-22 21:20:14.826298', 6);
INSERT INTO public.otp_challenges VALUES ('3697cd9b-b92b-4c1b-9fb4-6764ab131adb', 0, '$2a$10$UbXNES70bffu56X2DlFyeuDS6yjfTAZbFw.ZD3bzIVQAB5lVMm39.', '2026-06-22 22:27:06.465913', '2026-06-22 22:25:50.519131', '2026-06-22 22:30:50.519131', 5, 'LOGIN', '2026-06-22 22:26:50.519131', 0, '2026-06-22 22:27:06.479439', 6);
INSERT INTO public.otp_challenges VALUES ('41bc31f5-d6b2-4e20-a702-bb7c51704d20', 0, '$2a$10$0u9qxEcgzmhSwL7BPL.S9eiXaswH9qayDAQN.nQmuKQlkpK7v.Ati', '2026-06-22 22:38:28.693115', '2026-06-22 22:37:58.503495', '2026-06-22 22:42:58.503495', 5, 'LOGIN', '2026-06-22 22:38:58.503495', 0, '2026-06-22 22:38:28.698642', 6);
INSERT INTO public.otp_challenges VALUES ('393e26b0-848f-417f-ac35-c3a5ca6262b6', 0, '$2a$10$O4u6ABYS56sL.oOS1rJ6yuMQdpg3BMtJTUvKaPGhndIamtYLq34dG', '2026-06-22 22:50:52.139359', '2026-06-22 22:50:33.965945', '2026-06-22 22:55:33.965945', 5, 'FORGOT_PASSWORD', '2026-06-22 22:51:33.965945', 0, '2026-06-22 22:50:52.145352', 6);
INSERT INTO public.otp_challenges VALUES ('e71a5355-6302-4bad-aee9-aee99ecfe8b6', 0, '$2a$10$T3ZKFuS5ZGtYIW1ILT8g1epO0EezhmTwfDnnYZ5/wM/sPjLmTdbbC', '2026-06-22 22:51:37.424469', '2026-06-22 22:51:21.153927', '2026-06-22 22:56:21.153927', 5, 'LOGIN', '2026-06-22 22:52:21.153927', 0, '2026-06-22 22:51:37.444014', 6);
INSERT INTO public.otp_challenges VALUES ('3ea26577-c97e-4821-8b90-e77765bd39eb', 0, '$2a$10$wQXLKbM4a44atA9fEzboDOSBkxvfEAsSkoy4t0qTriXw5dTbk5Sou', '2026-06-22 23:11:26.820849', '2026-06-22 23:03:48.787775', '2026-06-22 23:08:48.787775', 5, 'LOGIN', '2026-06-22 23:04:48.787775', 0, '2026-06-22 23:03:48.787775', 17);
INSERT INTO public.otp_challenges VALUES ('85fb6fc9-a787-47cb-bdee-d1f59719b65b', 0, '$2a$10$tNTepAVJRTmO7tRrkBUx0OUH80k5iClcBKhI9mFqnrd3FB8li.hUm', '2026-06-22 23:11:45.181162', '2026-06-22 23:11:27.036104', '2026-06-22 23:16:27.036104', 5, 'LOGIN', '2026-06-22 23:12:27.036104', 0, '2026-06-22 23:11:45.464734', 17);
INSERT INTO public.otp_challenges VALUES ('a872f28a-7508-4d45-b748-0a8ccc5bd9f0', 0, '$2a$10$Dyjtol2bB17lO2IjMRQtu.orHhTWkefpc8KhqHVaDUoMV3cdeEus2', '2026-06-22 23:16:16.994438', '2026-06-22 23:15:51.439479', '2026-06-22 23:20:51.439479', 5, 'LOGIN', '2026-06-22 23:16:51.439479', 0, '2026-06-22 23:16:17.00045', 17);
INSERT INTO public.otp_challenges VALUES ('8ed10533-7618-40ee-afab-08496f2171c9', 0, '$2a$10$FL23jhB1bMwxYydR/ZCGKejRf7v/eBi8OpnyjSUVDRUZiSBngD6KC', '2026-06-22 23:17:42.525737', '2026-06-22 23:17:20.021245', '2026-06-22 23:22:20.021245', 5, 'LOGIN', '2026-06-22 23:18:20.021245', 0, '2026-06-22 23:17:42.53676', 6);
INSERT INTO public.otp_challenges VALUES ('b4eeb7d0-1499-4d67-abb3-347987c0b812', 0, '$2a$10$HbPGEJmhkz3Jf7lmUK/H8uEvBrjfF9FdzlDWFQr4aKHAJKD/APDfi', NULL, '2026-06-22 23:18:14.771058', '2026-06-22 23:23:14.771058', 5, 'LOGIN', '2026-06-22 23:19:14.771058', 0, '2026-06-22 23:18:14.771058', 17);
INSERT INTO public.otp_challenges VALUES ('2a66a892-7c25-4841-bcaa-bf104574a187', 0, '$2a$10$e5Wnua/XSlkbKPd2JhFngeRsfsCuBUtW7EuAD1/fhIfc4vMS1KK5W', '2026-06-22 23:19:57.696827', '2026-06-22 23:19:34.773326', '2026-06-22 23:24:34.773326', 5, 'LOGIN', '2026-06-22 23:20:34.773326', 0, '2026-06-22 23:19:57.703691', 5);
INSERT INTO public.otp_challenges VALUES ('002e13e2-d7d5-4675-8991-006844b0211e', 0, '$2a$10$At8WcG85JVa5F0wD/gVIIe.wz0RzCJ9Fsl.o2yj62tC8ClxQHgwLe', '2026-06-22 23:20:57.946834', '2026-06-22 23:20:33.192135', '2026-06-22 23:25:33.192135', 5, 'LOGIN', '2026-06-22 23:21:33.192135', 0, '2026-06-22 23:20:57.966018', 9);
INSERT INTO public.otp_challenges VALUES ('ed9195a9-d888-4891-b12e-6b828b2641a1', 0, '$2a$10$U2Ugje.miErhKIbvW832xey7244Zup0P5/1abq0PgZwNOp9BRtMRO', '2026-06-22 23:23:03.33175', '2026-06-22 23:22:47.681291', '2026-06-22 23:27:47.681291', 5, 'LOGIN', '2026-06-22 23:23:47.681291', 0, '2026-06-22 23:23:03.359776', 9);
INSERT INTO public.otp_challenges VALUES ('7febfdb0-7459-448b-aa0c-af10e71f7d16', 0, '$2a$10$bQFnoOVUWQbtRGV801ZpB.oCHECORV/4EavPlaF.D/ET77H39Z3f2', '2026-06-22 23:38:35.053544', '2026-06-22 22:09:02.346321', '2026-06-22 22:14:02.346321', 5, 'LOGIN', '2026-06-22 22:10:02.346321', 0, '2026-06-22 22:09:02.346321', 4);
INSERT INTO public.otp_challenges VALUES ('729898f5-c3ba-4c8b-954e-e607c58a3cb8', 0, '$2a$10$O58h/q3QitRiXQcwZbBHP.KjLnsae3b/79V1TvL2ecqXaru4RRAhG', '2026-06-22 23:39:03.311532', '2026-06-22 23:38:35.240274', '2026-06-22 23:43:35.240274', 5, 'LOGIN', '2026-06-22 23:39:35.240274', 0, '2026-06-22 23:38:35.240274', 4);
INSERT INTO public.otp_challenges VALUES ('c73dcf8d-3c6e-4940-a1d1-df187585085e', 0, '$2a$10$mqz7.JhlLYmDmu5YBBfJzeAEkhPuJ.pK3Q1Ktw8Wo7jaaaRNjINJW', '2026-06-22 23:42:19.59835', '2026-06-22 23:39:03.452184', '2026-06-22 23:46:56.876594', 5, 'LOGIN', '2026-06-22 23:42:56.876594', 1, '2026-06-22 23:41:59.996207', 4);
INSERT INTO public.otp_challenges VALUES ('fc5fe043-5bd4-4e88-8601-fa2269f83e51', 0, '$2a$10$lyZsDXDvLjBfC3GGr6UIm.plWA6wKLRfsUsbz63T1f.VOu1uS31iG', NULL, '2026-06-22 23:42:19.761244', '2026-06-22 23:47:19.761244', 5, 'LOGIN', '2026-06-22 23:43:19.761244', 0, '2026-06-22 23:42:19.761244', 4);
INSERT INTO public.otp_challenges VALUES ('d3081127-cdb2-488d-878e-4f97e31dd297', 0, '$2a$10$rlK13VTsdDQehyniUElJmO5HY5GOU8SYUuVN6KX0MWC8k2gHVuQ6q', NULL, '2026-06-22 23:43:00.578373', '2026-06-22 23:48:00.578373', 5, 'LOGIN', '2026-06-22 23:44:00.578373', 0, '2026-06-22 23:43:00.578373', 6);


--
-- TOC entry 5072 (class 0 OID 66125)
-- Dependencies: 228
-- Data for Name: password_reset_grants; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.password_reset_grants VALUES ('6c75e79c-2f9d-4eaf-82fd-ccf635dc3ffe', '2026-06-22 21:19:58.923269', '2026-06-22 21:29:58.923269', 'ea99580e28fe8a2cad7e95f37ff4d66eaf9229ed2617d9b5d3efb9aa8114ab2e', NULL, 1);
INSERT INTO public.password_reset_grants VALUES ('079add1c-0607-4b18-9bf5-310a1684210e', '2026-06-22 22:16:02.390265', '2026-06-22 22:26:02.390265', 'bfda71d0fe7afa9b00bbbbc06000296c1bbe62459dd9761dfd9fbf1cdb2968bb', NULL, 17);
INSERT INTO public.password_reset_grants VALUES ('a945ffa2-5d4b-4d4a-8d16-900cbf44fd9e', '2026-06-22 22:50:52.140352', '2026-06-22 23:00:52.140352', '30841dda8d6e68f2b26059cf792b30ee97efd5d591a3adfe846a11a38b2029a4', '2026-06-22 22:51:05.656039', 6);


--
-- TOC entry 5064 (class 0 OID 49265)
-- Dependencies: 220
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.permissions VALUES (1, '2026-06-07 01:00:34.127193', 'Melihat data user', 'auth.user.read', '2026-06-07 01:00:34.127193', true);
INSERT INTO public.permissions VALUES (2, '2026-06-07 01:00:34.253753', 'Mengelola user', 'auth.user.manage', '2026-06-07 01:00:34.253753', true);
INSERT INTO public.permissions VALUES (3, '2026-06-07 01:00:34.258753', 'Mengelola role dan permission', 'auth.role.manage', '2026-06-07 01:00:34.258753', true);
INSERT INTO public.permissions VALUES (4, '2026-06-07 01:00:34.265756', 'Melihat data organisasi', 'organization.read', '2026-06-07 01:00:34.265756', true);
INSERT INTO public.permissions VALUES (5, '2026-06-07 01:00:34.273776', 'Mengelola anggota, divisi, dan jabatan', 'organization.manage', '2026-06-07 01:00:34.273776', true);
INSERT INTO public.permissions VALUES (6, '2026-06-07 01:00:34.283839', 'Melihat tugas divisi', 'division.task.read', '2026-06-07 01:00:34.283839', true);
INSERT INTO public.permissions VALUES (7, '2026-06-07 01:00:34.289307', 'Mengelola tugas dan agenda divisi', 'division.task.manage', '2026-06-07 01:00:34.289307', true);
INSERT INTO public.permissions VALUES (8, '2026-06-07 01:00:34.295303', 'Membuat pengajuan operasional', 'request.create', '2026-06-07 01:00:34.295303', true);
INSERT INTO public.permissions VALUES (9, '2026-06-07 01:00:34.304319', 'Melihat pengajuan milik sendiri', 'request.read.own', '2026-06-07 01:00:34.304319', true);
INSERT INTO public.permissions VALUES (10, '2026-06-07 01:00:34.311302', 'Melihat seluruh pengajuan', 'request.read.all', '2026-06-07 01:00:34.311302', true);
INSERT INTO public.permissions VALUES (11, '2026-06-07 01:00:34.320304', 'Approval pengajuan oleh Ketua Divisi', 'request.approve.division', '2026-06-07 01:00:34.320304', true);
INSERT INTO public.permissions VALUES (12, '2026-06-07 01:00:34.326306', 'Approval pengajuan oleh Ketua PUB', 'request.approve.pub', '2026-06-07 01:00:34.326306', true);
INSERT INTO public.permissions VALUES (13, '2026-06-07 01:00:34.334303', 'Approval pengajuan oleh Pembina', 'request.approve.pembina', '2026-06-07 01:00:34.334303', true);
INSERT INTO public.permissions VALUES (14, '2026-06-07 01:00:34.340297', 'Melakukan pencairan dana', 'finance.disburse', '2026-06-07 01:00:34.340297', true);
INSERT INTO public.permissions VALUES (15, '2026-06-07 01:00:34.349302', 'Verifikasi settlement keuangan', 'finance.settlement.verify', '2026-06-07 01:00:34.349302', true);
INSERT INTO public.permissions VALUES (16, '2026-06-07 01:00:34.354313', 'Melihat laporan keuangan', 'finance.report.read', '2026-06-07 01:00:34.354313', true);
INSERT INTO public.permissions VALUES (17, '2026-06-07 01:00:34.360304', 'Mengelola arsip dokumen', 'archive.manage', '2026-06-07 01:00:34.360304', true);
INSERT INTO public.permissions VALUES (18, '2026-06-07 01:00:34.369313', 'Mengelola notifikasi', 'notification.manage', '2026-06-07 01:00:34.369313', true);
INSERT INTO public.permissions VALUES (19, '2026-06-07 01:00:34.37432', 'Melihat laporan umum', 'report.read', '2026-06-07 01:00:34.37432', true);
INSERT INTO public.permissions VALUES (20, '2026-06-22 20:52:06.236689', 'Melihat aset', 'asset.read', '2026-06-22 20:52:06.236689', true);
INSERT INTO public.permissions VALUES (21, '2026-06-22 20:52:06.579231', 'Mengelola data aset', 'asset.manage', '2026-06-22 20:52:06.579231', true);
INSERT INTO public.permissions VALUES (22, '2026-06-22 20:52:06.623274', 'Mengajukan peminjaman aset', 'asset.borrow.create', '2026-06-22 20:52:06.623274', true);
INSERT INTO public.permissions VALUES (23, '2026-06-22 20:52:06.640481', 'Melihat peminjaman sendiri', 'asset.borrow.read.own', '2026-06-22 20:52:06.640481', true);
INSERT INTO public.permissions VALUES (24, '2026-06-22 20:52:06.655757', 'Melihat semua peminjaman', 'asset.borrow.read.all', '2026-06-22 20:52:06.655757', true);
INSERT INTO public.permissions VALUES (25, '2026-06-22 20:52:06.69788', 'Merespons permohonan peminjaman', 'asset.borrow.approve', '2026-06-22 20:52:06.69788', true);
INSERT INTO public.permissions VALUES (26, '2026-06-22 20:52:06.719887', 'Menyerahkan aset', 'asset.borrow.handover', '2026-06-22 20:52:06.719887', true);
INSERT INTO public.permissions VALUES (27, '2026-06-22 20:52:06.739958', 'Memverifikasi pengembalian aset', 'asset.return.verify', '2026-06-22 20:52:06.739958', true);
INSERT INTO public.permissions VALUES (28, '2026-06-22 20:52:06.763027', 'Mengelola kondisi aset', 'asset.condition.manage', '2026-06-22 20:52:06.763027', true);
INSERT INTO public.permissions VALUES (29, '2026-06-22 20:52:06.790844', 'Melihat jadwal piket kebersihan', 'cleanliness.schedule.read', '2026-06-22 20:52:06.790844', true);
INSERT INTO public.permissions VALUES (30, '2026-06-22 20:52:06.805374', 'Mengelola jadwal piket kebersihan', 'cleanliness.schedule.manage', '2026-06-22 20:52:06.805374', true);
INSERT INTO public.permissions VALUES (31, '2026-06-22 20:52:06.829508', 'Mengisi presensi piket', 'cleanliness.attendance.create', '2026-06-22 20:52:06.829508', true);
INSERT INTO public.permissions VALUES (32, '2026-06-22 20:52:06.856516', 'Melihat presensi piket', 'cleanliness.attendance.read', '2026-06-22 20:52:06.856516', true);
INSERT INTO public.permissions VALUES (33, '2026-06-22 20:52:06.875215', 'Mengelola poin reward piket', 'cleanliness.point.manage', '2026-06-22 20:52:06.875215', true);
INSERT INTO public.permissions VALUES (34, '2026-06-22 20:52:06.895771', 'Mengelola poin pelanggaran piket', 'cleanliness.violation.manage', '2026-06-22 20:52:06.895771', true);
INSERT INTO public.permissions VALUES (35, '2026-06-22 20:52:06.921064', 'Melihat laporan piket kebersihan', 'cleanliness.report.read', '2026-06-22 20:52:06.921064', true);
INSERT INTO public.permissions VALUES (36, '2026-06-22 20:52:06.932067', 'Melihat jadwal aktivitas bahasa Inggris', 'english.activity.read', '2026-06-22 20:52:06.932067', true);
INSERT INTO public.permissions VALUES (37, '2026-06-22 20:52:06.951081', 'Mengelola aktivitas bahasa Inggris', 'english.activity.manage', '2026-06-22 20:52:06.951081', true);
INSERT INTO public.permissions VALUES (38, '2026-06-22 20:52:06.962613', 'Membuat setoran bahasa Inggris', 'english.deposit.create', '2026-06-22 20:52:06.962613', true);
INSERT INTO public.permissions VALUES (39, '2026-06-22 20:52:06.976616', 'Melihat setoran bahasa Inggris sendiri', 'english.deposit.read.own', '2026-06-22 20:52:06.976616', true);
INSERT INTO public.permissions VALUES (40, '2026-06-22 20:52:07.001736', 'Melihat seluruh setoran bahasa Inggris', 'english.deposit.read.all', '2026-06-22 20:52:07.001736', true);
INSERT INTO public.permissions VALUES (41, '2026-06-22 20:52:07.030255', 'Memverifikasi setoran bahasa Inggris', 'english.deposit.verify', '2026-06-22 20:52:07.030255', true);
INSERT INTO public.permissions VALUES (42, '2026-06-22 20:52:07.072808', 'Melihat laporan aktivitas bahasa Inggris', 'english.report.read', '2026-06-22 20:52:07.072808', true);
INSERT INTO public.permissions VALUES (43, '2026-06-22 20:52:07.103821', 'Melihat konten publik admin', 'public.content.read', '2026-06-22 20:52:07.103821', true);
INSERT INTO public.permissions VALUES (44, '2026-06-22 20:52:07.128467', 'Mengelola program, fasilitas, dan testimoni', 'public.content.manage', '2026-06-22 20:52:07.128467', true);
INSERT INTO public.permissions VALUES (45, '2026-06-22 20:52:07.18627', 'Mengelola profil publik organisasi', 'public.organization.manage', '2026-06-22 20:52:07.18627', true);
INSERT INTO public.permissions VALUES (46, '2026-06-22 20:52:07.228391', 'Mengelola publikasi kegiatan', 'public.activity.manage', '2026-06-22 20:52:07.228391', true);
INSERT INTO public.permissions VALUES (47, '2026-06-22 20:52:07.281891', 'Mengelola metadata media publik', 'public.media.manage', '2026-06-22 20:52:07.281891', true);
INSERT INTO public.permissions VALUES (48, '2026-06-22 20:52:07.300909', 'Mengirim notifikasi manual', 'notification.send', '2026-06-22 20:52:07.300909', true);
INSERT INTO public.permissions VALUES (49, '2026-06-22 20:52:07.327981', 'Melihat notifikasi', 'notification.read', '2026-06-22 20:52:07.327981', true);
INSERT INTO public.permissions VALUES (50, '2026-06-22 20:52:07.368153', 'Mencoba ulang notifikasi gagal', 'notification.retry', '2026-06-22 20:52:07.368153', true);
INSERT INTO public.permissions VALUES (51, '2026-06-22 20:52:07.411571', 'Mengekspor laporan', 'report.export', '2026-06-22 20:52:07.411571', true);
INSERT INTO public.permissions VALUES (52, '2026-06-22 20:52:07.436851', 'Mengimpor data laporan', 'report.import', '2026-06-22 20:52:07.436851', true);
INSERT INTO public.permissions VALUES (53, '2026-06-22 20:52:07.478416', 'Melihat log penjadwalan', 'scheduler.log.read', '2026-06-22 20:52:07.478416', true);


--
-- TOC entry 5065 (class 0 OID 49274)
-- Dependencies: 221
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role_permissions VALUES (2, 14);
INSERT INTO public.role_permissions VALUES (2, 1);
INSERT INTO public.role_permissions VALUES (2, 3);
INSERT INTO public.role_permissions VALUES (2, 10);
INSERT INTO public.role_permissions VALUES (2, 15);
INSERT INTO public.role_permissions VALUES (2, 19);
INSERT INTO public.role_permissions VALUES (2, 4);
INSERT INTO public.role_permissions VALUES (2, 13);
INSERT INTO public.role_permissions VALUES (2, 17);
INSERT INTO public.role_permissions VALUES (2, 5);
INSERT INTO public.role_permissions VALUES (2, 7);
INSERT INTO public.role_permissions VALUES (2, 16);
INSERT INTO public.role_permissions VALUES (2, 2);
INSERT INTO public.role_permissions VALUES (2, 12);
INSERT INTO public.role_permissions VALUES (2, 11);
INSERT INTO public.role_permissions VALUES (2, 9);
INSERT INTO public.role_permissions VALUES (2, 18);
INSERT INTO public.role_permissions VALUES (2, 6);
INSERT INTO public.role_permissions VALUES (2, 8);
INSERT INTO public.role_permissions VALUES (3, 4);
INSERT INTO public.role_permissions VALUES (3, 10);
INSERT INTO public.role_permissions VALUES (3, 6);
INSERT INTO public.role_permissions VALUES (3, 13);
INSERT INTO public.role_permissions VALUES (3, 16);
INSERT INTO public.role_permissions VALUES (3, 19);
INSERT INTO public.role_permissions VALUES (4, 12);
INSERT INTO public.role_permissions VALUES (4, 17);
INSERT INTO public.role_permissions VALUES (4, 4);
INSERT INTO public.role_permissions VALUES (4, 19);
INSERT INTO public.role_permissions VALUES (4, 6);
INSERT INTO public.role_permissions VALUES (4, 7);
INSERT INTO public.role_permissions VALUES (4, 10);
INSERT INTO public.role_permissions VALUES (4, 16);
INSERT INTO public.role_permissions VALUES (4, 5);
INSERT INTO public.role_permissions VALUES (4, 8);
INSERT INTO public.role_permissions VALUES (5, 7);
INSERT INTO public.role_permissions VALUES (5, 4);
INSERT INTO public.role_permissions VALUES (5, 8);
INSERT INTO public.role_permissions VALUES (5, 11);
INSERT INTO public.role_permissions VALUES (5, 6);
INSERT INTO public.role_permissions VALUES (5, 9);
INSERT INTO public.role_permissions VALUES (6, 5);
INSERT INTO public.role_permissions VALUES (6, 19);
INSERT INTO public.role_permissions VALUES (6, 17);
INSERT INTO public.role_permissions VALUES (6, 4);
INSERT INTO public.role_permissions VALUES (7, 15);
INSERT INTO public.role_permissions VALUES (7, 4);
INSERT INTO public.role_permissions VALUES (7, 19);
INSERT INTO public.role_permissions VALUES (7, 16);
INSERT INTO public.role_permissions VALUES (7, 14);
INSERT INTO public.role_permissions VALUES (7, 10);
INSERT INTO public.role_permissions VALUES (8, 4);
INSERT INTO public.role_permissions VALUES (8, 16);
INSERT INTO public.role_permissions VALUES (8, 19);
INSERT INTO public.role_permissions VALUES (1, 4);
INSERT INTO public.role_permissions VALUES (1, 6);
INSERT INTO public.role_permissions VALUES (1, 9);
INSERT INTO public.role_permissions VALUES (1, 8);
INSERT INTO public.role_permissions VALUES (2, 29);
INSERT INTO public.role_permissions VALUES (2, 40);
INSERT INTO public.role_permissions VALUES (2, 48);
INSERT INTO public.role_permissions VALUES (2, 22);
INSERT INTO public.role_permissions VALUES (2, 49);
INSERT INTO public.role_permissions VALUES (2, 36);
INSERT INTO public.role_permissions VALUES (2, 47);
INSERT INTO public.role_permissions VALUES (2, 37);
INSERT INTO public.role_permissions VALUES (2, 51);
INSERT INTO public.role_permissions VALUES (2, 33);
INSERT INTO public.role_permissions VALUES (2, 24);
INSERT INTO public.role_permissions VALUES (2, 44);
INSERT INTO public.role_permissions VALUES (2, 32);
INSERT INTO public.role_permissions VALUES (2, 35);
INSERT INTO public.role_permissions VALUES (2, 21);
INSERT INTO public.role_permissions VALUES (2, 27);
INSERT INTO public.role_permissions VALUES (2, 46);
INSERT INTO public.role_permissions VALUES (2, 50);
INSERT INTO public.role_permissions VALUES (2, 31);
INSERT INTO public.role_permissions VALUES (2, 38);
INSERT INTO public.role_permissions VALUES (2, 41);
INSERT INTO public.role_permissions VALUES (2, 28);
INSERT INTO public.role_permissions VALUES (2, 26);
INSERT INTO public.role_permissions VALUES (2, 39);
INSERT INTO public.role_permissions VALUES (2, 43);
INSERT INTO public.role_permissions VALUES (2, 20);
INSERT INTO public.role_permissions VALUES (2, 53);
INSERT INTO public.role_permissions VALUES (2, 23);
INSERT INTO public.role_permissions VALUES (2, 45);
INSERT INTO public.role_permissions VALUES (2, 52);
INSERT INTO public.role_permissions VALUES (2, 25);
INSERT INTO public.role_permissions VALUES (2, 34);
INSERT INTO public.role_permissions VALUES (2, 30);
INSERT INTO public.role_permissions VALUES (2, 42);
INSERT INTO public.role_permissions VALUES (11, 45);
INSERT INTO public.role_permissions VALUES (11, 46);
INSERT INTO public.role_permissions VALUES (11, 47);
INSERT INTO public.role_permissions VALUES (11, 43);
INSERT INTO public.role_permissions VALUES (11, 44);
INSERT INTO public.role_permissions VALUES (10, 34);
INSERT INTO public.role_permissions VALUES (10, 37);
INSERT INTO public.role_permissions VALUES (10, 32);
INSERT INTO public.role_permissions VALUES (10, 38);
INSERT INTO public.role_permissions VALUES (10, 42);
INSERT INTO public.role_permissions VALUES (10, 40);
INSERT INTO public.role_permissions VALUES (10, 39);
INSERT INTO public.role_permissions VALUES (10, 41);
INSERT INTO public.role_permissions VALUES (10, 30);
INSERT INTO public.role_permissions VALUES (10, 33);
INSERT INTO public.role_permissions VALUES (10, 36);
INSERT INTO public.role_permissions VALUES (10, 29);
INSERT INTO public.role_permissions VALUES (10, 31);
INSERT INTO public.role_permissions VALUES (10, 35);
INSERT INTO public.role_permissions VALUES (10, 43);
INSERT INTO public.role_permissions VALUES (3, 51);
INSERT INTO public.role_permissions VALUES (3, 40);
INSERT INTO public.role_permissions VALUES (3, 29);
INSERT INTO public.role_permissions VALUES (3, 35);
INSERT INTO public.role_permissions VALUES (3, 24);
INSERT INTO public.role_permissions VALUES (3, 48);
INSERT INTO public.role_permissions VALUES (3, 49);
INSERT INTO public.role_permissions VALUES (3, 36);
INSERT INTO public.role_permissions VALUES (3, 20);
INSERT INTO public.role_permissions VALUES (3, 32);
INSERT INTO public.role_permissions VALUES (3, 42);
INSERT INTO public.role_permissions VALUES (3, 53);
INSERT INTO public.role_permissions VALUES (4, 28);
INSERT INTO public.role_permissions VALUES (4, 42);
INSERT INTO public.role_permissions VALUES (4, 47);
INSERT INTO public.role_permissions VALUES (4, 25);
INSERT INTO public.role_permissions VALUES (4, 45);
INSERT INTO public.role_permissions VALUES (4, 48);
INSERT INTO public.role_permissions VALUES (4, 44);
INSERT INTO public.role_permissions VALUES (4, 43);
INSERT INTO public.role_permissions VALUES (4, 21);
INSERT INTO public.role_permissions VALUES (4, 24);
INSERT INTO public.role_permissions VALUES (4, 36);
INSERT INTO public.role_permissions VALUES (4, 32);
INSERT INTO public.role_permissions VALUES (4, 46);
INSERT INTO public.role_permissions VALUES (4, 26);
INSERT INTO public.role_permissions VALUES (4, 27);
INSERT INTO public.role_permissions VALUES (4, 51);
INSERT INTO public.role_permissions VALUES (4, 35);
INSERT INTO public.role_permissions VALUES (4, 40);
INSERT INTO public.role_permissions VALUES (4, 49);
INSERT INTO public.role_permissions VALUES (4, 20);
INSERT INTO public.role_permissions VALUES (4, 53);
INSERT INTO public.role_permissions VALUES (4, 29);
INSERT INTO public.role_permissions VALUES (5, 23);
INSERT INTO public.role_permissions VALUES (5, 20);
INSERT INTO public.role_permissions VALUES (5, 22);
INSERT INTO public.role_permissions VALUES (6, 51);
INSERT INTO public.role_permissions VALUES (6, 45);
INSERT INTO public.role_permissions VALUES (6, 48);
INSERT INTO public.role_permissions VALUES (6, 52);
INSERT INTO public.role_permissions VALUES (6, 53);
INSERT INTO public.role_permissions VALUES (6, 49);
INSERT INTO public.role_permissions VALUES (6, 50);
INSERT INTO public.role_permissions VALUES (6, 43);
INSERT INTO public.role_permissions VALUES (7, 51);
INSERT INTO public.role_permissions VALUES (8, 51);
INSERT INTO public.role_permissions VALUES (9, 4);
INSERT INTO public.role_permissions VALUES (9, 21);
INSERT INTO public.role_permissions VALUES (9, 20);
INSERT INTO public.role_permissions VALUES (9, 26);
INSERT INTO public.role_permissions VALUES (9, 25);
INSERT INTO public.role_permissions VALUES (9, 24);
INSERT INTO public.role_permissions VALUES (9, 27);
INSERT INTO public.role_permissions VALUES (9, 28);
INSERT INTO public.role_permissions VALUES (1, 31);
INSERT INTO public.role_permissions VALUES (1, 38);
INSERT INTO public.role_permissions VALUES (1, 23);
INSERT INTO public.role_permissions VALUES (1, 39);
INSERT INTO public.role_permissions VALUES (1, 20);
INSERT INTO public.role_permissions VALUES (1, 29);
INSERT INTO public.role_permissions VALUES (1, 22);
INSERT INTO public.role_permissions VALUES (1, 36);


--
-- TOC entry 5067 (class 0 OID 49282)
-- Dependencies: 223
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.roles VALUES (1, true, '2026-05-30 00:25:11.221013', 'Role default untuk Anggota', 'ANGGOTA', '2026-05-30 00:25:11.221013');
INSERT INTO public.roles VALUES (2, true, '2026-06-07 01:00:34.393837', 'Akses penuh sistem', 'SUPER_ADMIN', '2026-06-07 01:00:34.393837');
INSERT INTO public.roles VALUES (3, true, '2026-06-07 01:00:34.430852', 'Pembina organisasi', 'PEMBINA', '2026-06-07 01:00:34.430852');
INSERT INTO public.roles VALUES (4, true, '2026-06-07 01:00:34.437835', 'Ketua PUB', 'KETUA_PUB', '2026-06-07 01:00:34.437835');
INSERT INTO public.roles VALUES (5, true, '2026-06-07 01:00:34.443836', 'Ketua Divisi', 'KETUA_DIVISI', '2026-06-07 01:00:34.443836');
INSERT INTO public.roles VALUES (6, true, '2026-06-07 01:00:34.452832', 'Sekretaris organisasi', 'SEKRETARIS', '2026-06-07 01:00:34.452832');
INSERT INTO public.roles VALUES (7, true, '2026-06-07 01:00:34.459834', 'Bendahara internal', 'BENDAHARA_INTERNAL', '2026-06-07 01:00:34.459834');
INSERT INTO public.roles VALUES (8, true, '2026-06-07 01:00:34.468856', 'Bendahara eksternal', 'BENDAHARA_EKSTERNAL', '2026-06-07 01:00:34.469837');
INSERT INTO public.roles VALUES (9, true, '2026-06-22 20:52:07.845411', 'Pemeriksa dan pengelola operasional aset', 'CHECKER', '2026-06-22 20:52:07.845411');
INSERT INTO public.roles VALUES (10, true, '2026-06-22 20:52:07.93203', 'Koordinator piket', 'KOORDINATOR', '2026-06-22 20:52:07.933031');
INSERT INTO public.roles VALUES (11, true, '2026-06-22 20:52:07.989076', 'Pengelola publikasi dan media organisasi', 'HUMAS', '2026-06-22 20:52:07.989076');


--
-- TOC entry 5073 (class 0 OID 66135)
-- Dependencies: 229
-- Data for Name: trusted_devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.trusted_devices VALUES ('f4393e62-7ba7-4028-ab25-c34071ddd277', '2026-06-22 21:10:16.015974', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 21:10:16.015974', '127.0.0.1', '2026-06-22 21:10:16.015974', '2026-06-22 21:10:52.078691', 'fcf68f404f4485f3a236178465c58af9214a27b473c8f2e5152f14353786722b', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 6);
INSERT INTO public.trusted_devices VALUES ('ad4c14ac-3503-44b2-bd5b-8fcedf15852d', '2026-06-22 22:27:06.484971', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 22:27:06.484971', '127.0.0.1', '2026-06-22 22:27:06.484971', '2026-06-22 22:36:55.390243', 'ed4566cf61ff491fd466697f0cc282e2e2d4971687ec651aeec70fc3ecba261c', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 6);
INSERT INTO public.trusted_devices VALUES ('07a45df0-7360-4eb7-8f87-8b0a47da4602', '2026-06-22 22:38:28.703643', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 22:38:28.703643', '127.0.0.1', '2026-06-22 22:38:28.703643', '2026-06-22 22:47:59.113706', 'd636c0b36eae281d9c76afbbb5f11ef20ce39dc9ac54959a3064ef32558a3a73', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 6);
INSERT INTO public.trusted_devices VALUES ('4bad6042-d211-47e3-ac8b-ebe467cb0be8', '2026-06-22 22:51:37.456273', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 22:51:37.456273', '127.0.0.1', '2026-06-22 22:51:37.456273', '2026-06-22 22:53:19.683558', 'dac02f61041bac0b8d7c34beb5020a5f025f836554b5d351c2aadba36d46e5ff', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 6);
INSERT INTO public.trusted_devices VALUES ('70853ac5-e097-4b04-9635-11bda2e4474f', '2026-06-22 23:11:45.484024', 'Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36', '2026-06-29 23:11:45.484024', '127.0.0.1', '2026-06-22 23:11:45.484024', '2026-06-22 23:14:03.001077', 'a9c1e277fd4ca4bc68387a02dbf68dcb1413f8cb091eafb591795f480984d4d6', 'Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36', 17);
INSERT INTO public.trusted_devices VALUES ('213f7db9-3999-43de-8dff-efc8517e8636', '2026-06-22 23:16:17.005457', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 23:16:17.005457', '127.0.0.1', '2026-06-22 23:16:17.005457', '2026-06-22 23:16:39.706784', '3a520ff3f59c0fa4e248253f80aeca4fba2a2669b55e9f2a251fdddefd58cd63', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 17);
INSERT INTO public.trusted_devices VALUES ('a1179c6d-02d8-4f45-b321-62dc96a32cb3', '2026-06-22 23:17:42.545759', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 23:17:42.545759', '127.0.0.1', '2026-06-22 23:17:42.545759', '2026-06-22 23:18:59.847052', 'e42de31d3e1d0b05f33475f44ebdde2d7c9ccb4ce68560d2a915b593fd3751a4', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 6);
INSERT INTO public.trusted_devices VALUES ('9685113c-a310-4973-9f5b-e51bfa6aa233', '2026-06-22 23:19:57.70769', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 23:19:57.70769', '127.0.0.1', '2026-06-22 23:19:57.70769', '2026-06-22 23:20:06.213551', '73f567571be10564a6087778e09360a4e66361cf8e4d129d32b1dce05ecfaf95', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 5);
INSERT INTO public.trusted_devices VALUES ('7c9a1c6c-658e-4f5e-a900-126dea167487', '2026-06-22 23:20:57.981548', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 23:20:57.981548', '127.0.0.1', '2026-06-22 23:20:57.981548', '2026-06-22 23:21:28.123849', '7cf0242cdeb9c8ca9dfb442fb4a065c3da92dcb6f24a27eb563cf78b834a3d9d', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 9);
INSERT INTO public.trusted_devices VALUES ('87f55b93-3502-4657-8d4f-c81a560cb2ff', '2026-06-22 23:23:03.389315', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', '2026-06-29 23:23:03.389315', '127.0.0.1', '2026-06-22 23:23:03.389315', '2026-06-22 23:23:29.327375', 'aa4aecea4c269f8c122a930f996bbe5756a1671a14f1f7f4652be5a814f79982', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36', 9);


--
-- TOC entry 5068 (class 0 OID 49292)
-- Dependencies: 224
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.user_roles VALUES (1, 1);
INSERT INTO public.user_roles VALUES (2, 1);
INSERT INTO public.user_roles VALUES (2, 2);
INSERT INTO public.user_roles VALUES (3, 2);
INSERT INTO public.user_roles VALUES (4, 2);
INSERT INTO public.user_roles VALUES (5, 3);
INSERT INTO public.user_roles VALUES (6, 4);
INSERT INTO public.user_roles VALUES (7, 1);
INSERT INTO public.user_roles VALUES (8, 6);
INSERT INTO public.user_roles VALUES (9, 7);
INSERT INTO public.user_roles VALUES (10, 8);
INSERT INTO public.user_roles VALUES (11, 1);
INSERT INTO public.user_roles VALUES (12, 1);
INSERT INTO public.user_roles VALUES (13, 5);
INSERT INTO public.user_roles VALUES (14, 1);
INSERT INTO public.user_roles VALUES (15, 5);
INSERT INTO public.user_roles VALUES (16, 1);
INSERT INTO public.user_roles VALUES (17, 1);
INSERT INTO public.user_roles VALUES (18, 1);
INSERT INTO public.user_roles VALUES (19, 1);
INSERT INTO public.user_roles VALUES (20, 1);
INSERT INTO public.user_roles VALUES (21, 1);
INSERT INTO public.user_roles VALUES (22, 1);
INSERT INTO public.user_roles VALUES (23, 1);
INSERT INTO public.user_roles VALUES (24, 1);
INSERT INTO public.user_roles VALUES (25, 5);
INSERT INTO public.user_roles VALUES (26, 5);
INSERT INTO public.user_roles VALUES (27, 1);
INSERT INTO public.user_roles VALUES (28, 1);
INSERT INTO public.user_roles VALUES (29, 1);
INSERT INTO public.user_roles VALUES (30, 5);
INSERT INTO public.user_roles VALUES (31, 1);
INSERT INTO public.user_roles VALUES (32, 1);
INSERT INTO public.user_roles VALUES (33, 1);
INSERT INTO public.user_roles VALUES (34, 5);
INSERT INTO public.user_roles VALUES (35, 1);
INSERT INTO public.user_roles VALUES (36, 5);
INSERT INTO public.user_roles VALUES (37, 1);
INSERT INTO public.user_roles VALUES (38, 1);
INSERT INTO public.user_roles VALUES (39, 1);
INSERT INTO public.user_roles VALUES (40, 1);
INSERT INTO public.user_roles VALUES (41, 5);
INSERT INTO public.user_roles VALUES (42, 1);
INSERT INTO public.user_roles VALUES (43, 1);
INSERT INTO public.user_roles VALUES (44, 1);
INSERT INTO public.user_roles VALUES (9, 1);
INSERT INTO public.user_roles VALUES (10, 1);


--
-- TOC entry 5070 (class 0 OID 49300)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (3, true, '2026-06-18 01:56:14.383177', 'admin@example.com', 'Super Admin Orchestria', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-18 01:56:14.383177', false);
INSERT INTO public.users VALUES (1, true, '2026-05-30 00:25:11.53491', 'pangeranvalerensco@gmail.com', 'Pangeran Valerensco', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-05-30 00:25:11.53491', false);
INSERT INTO public.users VALUES (4, true, '2026-06-18 02:06:58.8072', 'admin@mailinator.com', 'Super Admin Orchestria', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-18 02:06:58.8072', false);
INSERT INTO public.users VALUES (2, true, '2026-06-07 01:32:13.864388', 'superadmin@mailinator.com', 'Super Admin Orchestria', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-07 01:32:13.864388', false);
INSERT INTO public.users VALUES (23, true, '2026-06-19 14:09:01.248919', 'miftahul.jannah.harahap@mailinator.com', 'Miftahul Jannah Harahap', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:01.248919', false);
INSERT INTO public.users VALUES (24, true, '2026-06-19 14:09:01.864707', 'dea.afrilia@mailinator.com', 'Dea Afrilia', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:01.864707', false);
INSERT INTO public.users VALUES (25, true, '2026-06-19 14:09:02.66932', 'zaky.setiawan@mailinator.com', 'Zaky Setiawan', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:02.66932', false);
INSERT INTO public.users VALUES (26, true, '2026-06-19 14:09:03.236622', 'fajar.sidik@mailinator.com', 'Fajar Sidik', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:03.236622', false);
INSERT INTO public.users VALUES (27, true, '2026-06-19 14:09:03.828249', 'alfarizi@mailinator.com', 'Alfarizi', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:03.828249', false);
INSERT INTO public.users VALUES (28, true, '2026-06-19 14:09:04.533698', 'apriliyanti@mailinator.com', 'Apriliyanti', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:04.533698', false);
INSERT INTO public.users VALUES (29, true, '2026-06-19 14:09:05.040914', 'sri.muthian@mailinator.com', 'Sri Muthian', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:05.040914', false);
INSERT INTO public.users VALUES (30, true, '2026-06-19 14:09:05.544633', 'muhammad.farid@mailinator.com', 'Muhammad Farid', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:05.544633', false);
INSERT INTO public.users VALUES (31, true, '2026-06-19 14:09:06.222889', 'azhar.farizi@mailinator.com', 'Azhar Farizi', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:06.222889', false);
INSERT INTO public.users VALUES (32, true, '2026-06-19 14:09:07.134815', 'ewi.lestari.harahap@mailinator.com', 'Ewi Lestari Harahap', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:07.134815', false);
INSERT INTO public.users VALUES (33, true, '2026-06-19 14:09:07.604119', 'yusri.hasanah@mailinator.com', 'Yusri Hasanah', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:07.604119', false);
INSERT INTO public.users VALUES (34, true, '2026-06-19 14:09:08.061565', 'ahmad.zaki.hosammido@mailinator.com', 'Ahmad Zaki Hosammido', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:08.061565', false);
INSERT INTO public.users VALUES (35, true, '2026-06-19 14:09:08.652449', 'ade.dermawan@mailinator.com', 'Ade Dermawan', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:08.652449', false);
INSERT INTO public.users VALUES (36, true, '2026-06-19 14:09:09.106388', 'm.saroni@mailinator.com', 'M Saroni', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:09.106388', false);
INSERT INTO public.users VALUES (37, true, '2026-06-19 14:09:09.529443', 'ali.sahroji@mailinator.com', 'Ali Sahroji', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:09.529443', false);
INSERT INTO public.users VALUES (38, true, '2026-06-19 14:09:09.980276', 'sri.muthia.ningrum@mailinator.com', 'Sri Muthia Ningrum', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:09.980276', false);
INSERT INTO public.users VALUES (39, true, '2026-06-19 14:09:10.471673', 'galang.ponco.maulana@mailinator.com', 'Galang Ponco Maulana', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:10.471673', false);
INSERT INTO public.users VALUES (40, true, '2026-06-19 14:09:11.046643', 'padellan.riski@mailinator.com', 'Padellan Riski', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:11.046643', false);
INSERT INTO public.users VALUES (41, true, '2026-06-19 14:09:11.594433', 'm.haikal@mailinator.com', 'M Haikal', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:11.594433', false);
INSERT INTO public.users VALUES (42, true, '2026-06-19 14:09:12.012806', 'alfa.rizi@mailinator.com', 'Alfa Rizi', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:12.012806', false);
INSERT INTO public.users VALUES (43, true, '2026-06-19 14:09:12.493581', 'raja.tegar.albaihaqi@mailinator.com', 'Raja Tegar Albaihaqi', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:12.493581', false);
INSERT INTO public.users VALUES (44, true, '2026-06-19 14:09:12.984043', 'ulil.arsyad.ramadhan@mailinator.com', 'Ulil Arsyad Ramadhan', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:12.984043', false);
INSERT INTO public.users VALUES (17, true, '2026-06-19 14:08:57.397964', 'izhar.harahap@mailinator.com', 'Izhar Harahap', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-22 22:17:03.342626', false);
INSERT INTO public.users VALUES (6, true, '2026-06-19 14:08:47.182779', 'pangeran.valerensco.rivaldi.hutabarat@mailinator.com', 'Pangeran Valerensco Rivaldi Hutabarat', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-22 22:51:05.663579', false);
INSERT INTO public.users VALUES (5, true, '2026-06-19 14:08:45.500098', 'abdul.hafiz.tanjung@mailinator.com', 'Abdul Hafiz Tanjung', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:45.500098', false);
INSERT INTO public.users VALUES (7, true, '2026-06-19 14:08:48.148305', 'ikram.fuadi.rambe@mailinator.com', 'Ikram Fuadi Rambe', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:48.148305', false);
INSERT INTO public.users VALUES (8, true, '2026-06-19 14:08:49.427469', 'khalisha.ulfa.marsha@mailinator.com', 'Khalisha Ulfa Marsha', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:49.427469', false);
INSERT INTO public.users VALUES (9, true, '2026-06-19 14:08:50.404435', 'andini.siti.nuriyanti@mailinator.com', 'Andini Siti Nuriyanti', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:50.404435', false);
INSERT INTO public.users VALUES (10, true, '2026-06-19 14:08:51.241602', 'sri.rahayu.lestari@mailinator.com', 'Sri Rahayu Lestari', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:51.241602', false);
INSERT INTO public.users VALUES (11, true, '2026-06-19 14:08:52.059122', 'dedy.darmawan.simanjuntak@mailinator.com', 'Dedy Darmawan Simanjuntak', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:52.059122', false);
INSERT INTO public.users VALUES (12, true, '2026-06-19 14:08:52.856342', 'firman.suherman@mailinator.com', 'Firman Suherman', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:52.856342', false);
INSERT INTO public.users VALUES (13, true, '2026-06-19 14:08:53.838963', 'rickhy.ramadhan@mailinator.com', 'Rickhy Ramadhan', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:53.838963', false);
INSERT INTO public.users VALUES (14, true, '2026-06-19 14:08:54.996772', 'raysha.fauziyah.andani@mailinator.com', 'Raysha Fauziyah Andani', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:54.996772', false);
INSERT INTO public.users VALUES (15, true, '2026-06-19 14:08:55.723384', 'yudistira.syahputra@mailinator.com', 'Yudistira Syahputra', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:55.723384', false);
INSERT INTO public.users VALUES (16, true, '2026-06-19 14:08:56.40192', 'taufik.rahman.tanjung@mailinator.com', 'Taufik Rahman Tanjung', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:56.40192', false);
INSERT INTO public.users VALUES (18, true, '2026-06-19 14:08:58.012787', 'm.faiq.emil.fuadi@mailinator.com', 'M Faiq Emil Fuadi', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:58.012787', false);
INSERT INTO public.users VALUES (19, true, '2026-06-19 14:08:58.619399', 'alif.rifki.pratama@mailinator.com', 'Alif Rifki Pratama', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:58.619399', false);
INSERT INTO public.users VALUES (20, true, '2026-06-19 14:08:59.321748', 'dhea.firmasari@mailinator.com', 'Dhea Firmasari', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:59.321748', false);
INSERT INTO public.users VALUES (21, true, '2026-06-19 14:08:59.908577', 'nabila.monica@mailinator.com', 'Nabila Monica', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:08:59.908577', false);
INSERT INTO public.users VALUES (22, true, '2026-06-19 14:09:00.711145', 'ines.karlina@mailinator.com', 'Ines Karlina', '$2y$10$a.pwjXKEUwc59HqNAeXtqeGEDiYBibzHPJxxtVPBGzvWde3tmp1Pm', '2026-06-19 14:09:00.711145', false);


--
-- TOC entry 5080 (class 0 OID 0)
-- Dependencies: 219
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_id_seq', 53, true);


--
-- TOC entry 5081 (class 0 OID 0)
-- Dependencies: 222
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 11, true);


--
-- TOC entry 5082 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 44, true);


--
-- TOC entry 4905 (class 2606 OID 66124)
-- Name: otp_challenges otp_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_challenges
    ADD CONSTRAINT otp_challenges_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 66134)
-- Name: password_reset_grants password_reset_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_grants
    ADD CONSTRAINT password_reset_grants_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 49273)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 49280)
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 4895 (class 2606 OID 49291)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 66147)
-- Name: trusted_devices trusted_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trusted_devices
    ADD CONSTRAINT trusted_devices_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 49319)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4909 (class 2606 OID 66150)
-- Name: password_reset_grants uke15qi31wwa7n18vr0dkym7sg3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_grants
    ADD CONSTRAINT uke15qi31wwa7n18vr0dkym7sg3 UNIQUE (token_hash);


--
-- TOC entry 4897 (class 2606 OID 49317)
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- TOC entry 4891 (class 2606 OID 49315)
-- Name: permissions ukpnvtwliis6p05pn6i3ndjrqt2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT ukpnvtwliis6p05pn6i3ndjrqt2 UNIQUE (name);


--
-- TOC entry 4899 (class 2606 OID 49298)
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 4903 (class 2606 OID 49313)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 49320)
-- Name: role_permissions fkegdk29eiy7mdtefy5c7eirr6e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id);


--
-- TOC entry 4914 (class 2606 OID 49330)
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 4915 (class 2606 OID 49335)
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4913 (class 2606 OID 49325)
-- Name: role_permissions fkn5fotdgk8d1xvo8nav9uv3muc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id);


-- Completed on 2026-06-22 23:50:02

--
-- PostgreSQL database dump complete
--

\unrestrict rAGOv74VSDWPdUGydPLiCRgZAgdLwS379TzjfzBg1MIz7wxTsS5BY7myHSPtJKd

